Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Mouth  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Head  Person  Animals
Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Mouth  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Head  Person  Animals
Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Mouth  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Head  Person  Animals
TV_Monitor 
Screen  TV_Monitor 
Bottle 
Cap  Bottle 
Body  Bottle 
