Horse  Animal
Tail  Horse  Animal
Hoof  Horse  Animal
Leg  Horse  Animal
Hoof  Horse  Animal
Leg  Horse  Animal
Hoof  Horse  Animal
Leg  Horse  Animal
Hoof  Horse  Animal
Leg  Horse  Animal
Neck  Horse  Animal
Torso  Horse  Animal
Muzzle  Horse  Animal
Eye  Horse  Animal
Head  Horse  Animal
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Head  Person  Animal
