variant 20 Cow  Animal
variant 70 Leg  Cow  Animal
variant 118 Torso  Cow  Animal
variant 84 Muzzle  Cow  Animal
variant 28 Ear  Cow  Animal
variant 50 Head  Cow  Animal
variant 20 Cow  Animal
variant 114 Tail  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 91 Neck  Cow  Animal
variant 118 Torso  Cow  Animal
variant 84 Muzzle  Cow  Animal
variant 50 Head  Cow  Animal
