Aeroplane  Vehicle
Stern  Aeroplane  Vehicle
Body  Aeroplane  Vehicle
Aeroplane  Vehicle
Stern  Aeroplane  Vehicle
Artifact_Wing  Aeroplane  Vehicle
Body  Aeroplane  Vehicle
Aeroplane  Vehicle
Stern  Aeroplane  Vehicle
Artifact_Wing  Aeroplane  Vehicle
Artifact_Wing  Aeroplane  Vehicle
Body  Aeroplane  Vehicle
Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Bodywork  Car  Vehicle
