Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Eyebrow  Person  Animal
Eyebrow  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Head  Person  Animal
Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Head  Person  Animal
Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Eyebrow  Person  Animal
Eyebrow  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Head  Person  Animal
Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Head  Person  Animal
Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Eyebrow  Person  Animal
Eyebrow  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Head  Person  Animal
Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Eyebrow  Person  Animal
Eyebrow  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Head  Person  Animal
TV_Monitor 
Screen  TV_Monitor 
