Person  Animals
Arm  Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Hair  Person  Animals
Eye  Person  Animals
Head  Person  Animals
Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Bodywork  Car  Vehicle
Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Door  Car  Vehicle
Bodywork  Car  Vehicle
