variant 98 Person  Animal
variant 44 Hand  Person  Animal
variant 2 Arm  Person  Animal
variant 87 Neck  Person  Animal
variant 122 Torso  Person  Animal
variant 95 Nose  Person  Animal
variant 43 Hair  Person  Animal
variant 32 Eye  Person  Animal
variant 55 Head  Person  Animal
variant 15 Car  Vehicle
variant 131 Window  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 24 Door  Car  Vehicle
variant 11 Bodywork  Car  Vehicle
variant 74 License_Plate  Car  Vehicle
variant 13 Bus  Vehicle
variant 130 Window  Bus  Vehicle
variant 130 Window  Bus  Vehicle
variant 126 Wheel  Bus  Vehicle
variant 126 Wheel  Bus  Vehicle
variant 126 Wheel  Bus  Vehicle
variant 56 Headlight  Bus  Vehicle
variant 56 Headlight  Bus  Vehicle
variant 77 Mirror  Bus  Vehicle
variant 77 Mirror  Bus  Vehicle
variant 10 Bodywork  Bus  Vehicle
variant 75 License_Plate  Bus  Vehicle
