variant 98 Person  Animal
variant 2 Arm  Person  Animal
variant 122 Torso  Person  Animal
variant 43 Hair  Person  Animal
variant 41 Eyebrow  Person  Animal
variant 32 Eye  Person  Animal
variant 26 Ear  Person  Animal
variant 55 Head  Person  Animal
variant 18 Chair 
variant 16 Cat  Animal
variant 65 Leg  Cat  Animal
variant 117 Torso  Cat  Animal
variant 49 Head  Cat  Animal
variant 33 Eye  Cat  Animal
variant 33 Eye  Cat  Animal
variant 25 Ear  Cat  Animal
variant 25 Ear  Cat  Animal
