Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Head  Person  Animal
Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Torso  Person  Animal
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Head  Person  Animal
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hair  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Nose  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Horse  Animal
Tail  Horse  Animal
Leg  Horse  Animal
Hoof  Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Hoof  Horse  Animal
Leg  Horse  Animal
Neck  Horse  Animal
Torso  Horse  Animal
Muzzle  Horse  Animal
Eye  Horse  Animal
Ear  Horse  Animal
Ear  Horse  Animal
Head  Horse  Animal
