Cow  Animal
Tail  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Neck  Cow  Animal
Torso  Cow  Animal
Muzzle  Cow  Animal
Head  Cow  Animal
Cow  Animal
Tail  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Neck  Cow  Animal
Torso  Cow  Animal
Muzzle  Cow  Animal
Eye  Cow  Animal
Ear  Cow  Animal
Head  Cow  Animal
Cow  Animal
Neck  Cow  Animal
Torso  Cow  Animal
Muzzle  Cow  Animal
Ear  Cow  Animal
Head  Cow  Animal
Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Torso  Cow  Animal
Head  Cow  Animal
Cow  Animal
Tail  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Torso  Cow  Animal
Ear  Cow  Animal
Head  Cow  Animal
Car  Vehicle
Bodywork  Car  Vehicle
Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
