variant 20 Cow  Animal
variant 114 Tail  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 91 Neck  Cow  Animal
variant 118 Torso  Cow  Animal
variant 84 Muzzle  Cow  Animal
variant 50 Head  Cow  Animal
variant 20 Cow  Animal
variant 114 Tail  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 91 Neck  Cow  Animal
variant 118 Torso  Cow  Animal
variant 84 Muzzle  Cow  Animal
variant 38 Eye  Cow  Animal
variant 28 Ear  Cow  Animal
variant 50 Head  Cow  Animal
variant 20 Cow  Animal
variant 91 Neck  Cow  Animal
variant 118 Torso  Cow  Animal
variant 84 Muzzle  Cow  Animal
variant 28 Ear  Cow  Animal
variant 50 Head  Cow  Animal
variant 20 Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 118 Torso  Cow  Animal
variant 50 Head  Cow  Animal
variant 20 Cow  Animal
variant 114 Tail  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 118 Torso  Cow  Animal
variant 28 Ear  Cow  Animal
variant 50 Head  Cow  Animal
variant 15 Car  Vehicle
variant 11 Bodywork  Car  Vehicle
variant 15 Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 11 Bodywork  Car  Vehicle
variant 74 License_Plate  Car  Vehicle
variant 15 Car  Vehicle
variant 131 Window  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 11 Bodywork  Car  Vehicle
variant 74 License_Plate  Car  Vehicle
variant 15 Car  Vehicle
variant 131 Window  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 11 Bodywork  Car  Vehicle
variant 74 License_Plate  Car  Vehicle
