variant 98 Person  Animal
variant 2 Arm  Person  Animal
variant 122 Torso  Person  Animal
variant 55 Head  Person  Animal
variant 98 Person  Animal
variant 43 Hair  Person  Animal
variant 55 Head  Person  Animal
variant 98 Person  Animal
variant 44 Hand  Person  Animal
variant 2 Arm  Person  Animal
variant 44 Hand  Person  Animal
variant 2 Arm  Person  Animal
variant 122 Torso  Person  Animal
variant 43 Hair  Person  Animal
variant 26 Ear  Person  Animal
variant 55 Head  Person  Animal
variant 12 Bottle 
variant 14 Cap  Bottle 
variant 8 Body  Bottle 
