Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Headlight  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
Person  Animals
Leg  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Mouth  Person  Animals
Eyebrow  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Cow  Animals
Torso  Cow  Animals
Muzzle  Cow  Animals
Eye  Cow  Animals
Ear  Cow  Animals
Head  Cow  Animals
