variant 15 Car  Vehicle
variant 11 Bodywork  Car  Vehicle
variant 79 Motorbike  Vehicle
variant 57 Headlight  Motorbike  Vehicle
variant 15 Car  Vehicle
variant 131 Window  Car  Vehicle
variant 11 Bodywork  Car  Vehicle
variant 74 License_Plate  Car  Vehicle
variant 15 Car  Vehicle
variant 131 Window  Car  Vehicle
variant 78 Mirror  Car  Vehicle
variant 11 Bodywork  Car  Vehicle
variant 74 License_Plate  Car  Vehicle
