Person  Animal
Arm  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Mouth  Person  Animal
Eyebrow  Person  Animal
Eyebrow  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Head  Person  Animal
Horse  Animal
Torso  Horse  Animal
Muzzle  Horse  Animal
Eye  Horse  Animal
Ear  Horse  Animal
Ear  Horse  Animal
Head  Horse  Animal
