Bird  Animals
Chair 
Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Mouth  Person  Animals
Eyebrow  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Head  Person  Animals
Bird  Animals
Tail  Bird  Animals
Leg  Bird  Animals
Leg  Bird  Animals
Animal_Wing  Bird  Animals
Animal_Wing  Bird  Animals
Torso  Bird  Animals
Head  Bird  Animals
