Bicycle  Vehicle
Handlebar  Bicycle  Vehicle
Chain_Wheel  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Mouth  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Head  Person  Animals
Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Mouth  Person  Animals
Head  Person  Animals
Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Head  Person  Animals
Person  Animals
Leg  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Head  Person  Animals
