Person  Animals
Torso  Person  Animals
Hair  Person  Animals
Head  Person  Animals
Person  Animals
Torso  Person  Animals
Head  Person  Animals
Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Hair  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Head  Person  Animals
Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Mouth  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Mouth  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Person  Animals
Hand  Person  Animals
Torso  Person  Animals
Hair  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Chair 
Chair 
Bottle 
Body  Bottle 
Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Mouth  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Dining_Table 
Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Mouth  Person  Animals
Eyebrow  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Ear  Person  Animals
Head  Person  Animals
