Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Eye  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Sheep  Animal
Neck  Sheep  Animal
Torso  Sheep  Animal
Muzzle  Sheep  Animal
Eye  Sheep  Animal
Ear  Sheep  Animal
Ear  Sheep  Animal
Head  Sheep  Animal
Bird  Animal
