Person  Animals
Leg  Person  Animals
Leg  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Wheel  Bus  Vehicle
Wheel  Bus  Vehicle
Wheel  Bus  Vehicle
Mirror  Bus  Vehicle
Bodywork  Bus  Vehicle
License_Plate  Bus  Vehicle
