Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Neck  Cow  Animal
Torso  Cow  Animal
Muzzle  Cow  Animal
Head  Cow  Animal
Cow  Animal
Tail  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Neck  Cow  Animal
Torso  Cow  Animal
Muzzle  Cow  Animal
Head  Cow  Animal
Cow  Animal
Tail  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Neck  Cow  Animal
Torso  Cow  Animal
Muzzle  Cow  Animal
Ear  Cow  Animal
Ear  Cow  Animal
Head  Cow  Animal
