variant 64 Horse  Animal
variant 93 Neck  Horse  Animal
variant 115 Torso  Horse  Animal
variant 81 Muzzle  Horse  Animal
variant 36 Eye  Horse  Animal
variant 30 Ear  Horse  Animal
variant 30 Ear  Horse  Animal
variant 51 Head  Horse  Animal
variant 20 Cow  Animal
variant 114 Tail  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 91 Neck  Cow  Animal
variant 118 Torso  Cow  Animal
variant 84 Muzzle  Cow  Animal
variant 28 Ear  Cow  Animal
variant 50 Head  Cow  Animal
