variant 106 Sofa 
variant 79 Motorbike  Vehicle
variant 57 Headlight  Motorbike  Vehicle
variant 129 Wheel  Motorbike  Vehicle
variant 5 Bicycle  Vehicle
variant 103 Saddle  Bicycle  Vehicle
variant 46 Handlebar  Bicycle  Vehicle
variant 128 Wheel  Bicycle  Vehicle
variant 128 Wheel  Bicycle  Vehicle
variant 5 Bicycle  Vehicle
variant 103 Saddle  Bicycle  Vehicle
variant 46 Handlebar  Bicycle  Vehicle
variant 128 Wheel  Bicycle  Vehicle
variant 128 Wheel  Bicycle  Vehicle
