Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Bodywork  Car  Vehicle
Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Bodywork  Car  Vehicle
Person  Animals
Leg  Person  Animals
Leg  Person  Animals
Arm  Person  Animals
Arm  Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Ear  Person  Animals
Head  Person  Animals
