Bird  Animal
Tail  Bird  Animal
Leg  Bird  Animal
Leg  Bird  Animal
Torso  Bird  Animal
Head  Bird  Animal
Bird  Animal
Leg  Bird  Animal
Leg  Bird  Animal
Torso  Bird  Animal
Beak  Bird  Animal
Eye  Bird  Animal
Eye  Bird  Animal
Head  Bird  Animal
Bird  Animal
Tail  Bird  Animal
Animal_Wing  Bird  Animal
Animal_Wing  Bird  Animal
Torso  Bird  Animal
Beak  Bird  Animal
Eye  Bird  Animal
Head  Bird  Animal
