Horse  Animals
Leg  Horse  Animals
Leg  Horse  Animals
Torso  Horse  Animals
Muzzle  Horse  Animals
Eye  Horse  Animals
Ear  Horse  Animals
Ear  Horse  Animals
Head  Horse  Animals
Bottle 
Cap  Bottle 
Body  Bottle 
Person  Animals
Leg  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Ear  Person  Animals
Head  Person  Animals
