Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Mouth  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Ear  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Cat  Animal
Tail  Cat  Animal
Leg  Cat  Animal
Leg  Cat  Animal
Leg  Cat  Animal
Neck  Cat  Animal
Torso  Cat  Animal
Head  Cat  Animal
Eye  Cat  Animal
Eye  Cat  Animal
Ear  Cat  Animal
Ear  Cat  Animal
