Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Torso  Horse  Animal
Muzzle  Horse  Animal
Eye  Horse  Animal
Ear  Horse  Animal
Ear  Horse  Animal
Head  Horse  Animal
Bottle 
Cap  Bottle 
Body  Bottle 
Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Ear  Person  Animal
Head  Person  Animal
