variant 6 Bird  Animal
variant 6 Bird  Animal
variant 112 Tail  Bird  Animal
variant 1 Animal_Wing  Bird  Animal
variant 121 Torso  Bird  Animal
variant 4 Beak  Bird  Animal
variant 47 Head  Bird  Animal
variant 6 Bird  Animal
variant 88 Neck  Bird  Animal
variant 121 Torso  Bird  Animal
variant 47 Head  Bird  Animal
variant 6 Bird  Animal
variant 112 Tail  Bird  Animal
variant 68 Leg  Bird  Animal
variant 88 Neck  Bird  Animal
variant 121 Torso  Bird  Animal
variant 4 Beak  Bird  Animal
variant 47 Head  Bird  Animal
variant 6 Bird  Animal
variant 112 Tail  Bird  Animal
variant 121 Torso  Bird  Animal
variant 6 Bird  Animal
variant 112 Tail  Bird  Animal
variant 68 Leg  Bird  Animal
variant 88 Neck  Bird  Animal
variant 121 Torso  Bird  Animal
variant 47 Head  Bird  Animal
variant 6 Bird  Animal
variant 112 Tail  Bird  Animal
variant 68 Leg  Bird  Animal
variant 88 Neck  Bird  Animal
variant 121 Torso  Bird  Animal
variant 4 Beak  Bird  Animal
variant 47 Head  Bird  Animal
variant 6 Bird  Animal
variant 112 Tail  Bird  Animal
variant 88 Neck  Bird  Animal
variant 121 Torso  Bird  Animal
variant 47 Head  Bird  Animal
variant 6 Bird  Animal
variant 112 Tail  Bird  Animal
variant 68 Leg  Bird  Animal
variant 68 Leg  Bird  Animal
variant 88 Neck  Bird  Animal
variant 121 Torso  Bird  Animal
variant 47 Head  Bird  Animal
variant 6 Bird  Animal
variant 112 Tail  Bird  Animal
variant 68 Leg  Bird  Animal
variant 88 Neck  Bird  Animal
variant 121 Torso  Bird  Animal
variant 4 Beak  Bird  Animal
variant 47 Head  Bird  Animal
variant 6 Bird  Animal
variant 112 Tail  Bird  Animal
variant 121 Torso  Bird  Animal
variant 47 Head  Bird  Animal
