variant 64 Horse  Animal
variant 113 Tail  Horse  Animal
variant 71 Leg  Horse  Animal
variant 71 Leg  Horse  Animal
variant 61 Hoof  Horse  Animal
variant 71 Leg  Horse  Animal
variant 71 Leg  Horse  Animal
variant 115 Torso  Horse  Animal
variant 98 Person  Animal
variant 87 Neck  Person  Animal
variant 122 Torso  Person  Animal
variant 95 Nose  Person  Animal
variant 80 Mouth  Person  Animal
variant 41 Eyebrow  Person  Animal
variant 41 Eyebrow  Person  Animal
variant 32 Eye  Person  Animal
variant 32 Eye  Person  Animal
variant 26 Ear  Person  Animal
variant 55 Head  Person  Animal
