Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Bodywork  Car  Vehicle
Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Eye  Person  Animals
Head  Person  Animals
Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Head  Person  Animals
