Horse  Animals
Tail  Horse  Animals
Leg  Horse  Animals
Leg  Horse  Animals
Hoof  Horse  Animals
Leg  Horse  Animals
Leg  Horse  Animals
Torso  Horse  Animals
Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Mouth  Person  Animals
Eyebrow  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Ear  Person  Animals
Head  Person  Animals
