Person  Animals
Leg  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Car  Vehicle
Window  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
