Boat  Vehicle
Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Person  Animal
Ear  Person  Animal
Head  Person  Animal
Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Head  Person  Animal
Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Person  Animal
Hair  Person  Animal
Head  Person  Animal
Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hair  Person  Animal
Head  Person  Animal
