variant 18 Chair 
variant 18 Chair 
variant 108 TV_Monitor 
variant 104 Screen  TV_Monitor 
variant 22 Dog  Animal
variant 66 Leg  Dog  Animal
variant 66 Leg  Dog  Animal
variant 66 Leg  Dog  Animal
variant 66 Leg  Dog  Animal
variant 116 Torso  Dog  Animal
variant 94 Nose  Dog  Animal
variant 83 Muzzle  Dog  Animal
variant 34 Eye  Dog  Animal
variant 27 Ear  Dog  Animal
variant 48 Head  Dog  Animal
variant 22 Dog  Animal
variant 66 Leg  Dog  Animal
variant 66 Leg  Dog  Animal
variant 92 Neck  Dog  Animal
variant 116 Torso  Dog  Animal
variant 94 Nose  Dog  Animal
variant 83 Muzzle  Dog  Animal
variant 34 Eye  Dog  Animal
variant 34 Eye  Dog  Animal
variant 27 Ear  Dog  Animal
variant 48 Head  Dog  Animal
