Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
Bicycle  Vehicle
Saddle  Bicycle  Vehicle
Handlebar  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
Person  Animal
Foot  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Eyebrow  Person  Animal
Ear  Person  Animal
Head  Person  Animal
