Car  Vehicle
Wheel  Car  Vehicle
Bodywork  Car  Vehicle
Cat  Animal
Leg  Cat  Animal
Leg  Cat  Animal
Torso  Cat  Animal
Head  Cat  Animal
Eye  Cat  Animal
Eye  Cat  Animal
Ear  Cat  Animal
Ear  Cat  Animal
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Mouth  Person  Animal
Eyebrow  Person  Animal
Eyebrow  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Ear  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Dog  Animal
Tail  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Neck  Dog  Animal
Torso  Dog  Animal
Muzzle  Dog  Animal
Ear  Dog  Animal
Head  Dog  Animal
Dog  Animal
Tail  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Torso  Dog  Animal
Head  Dog  Animal
