variant 98 Person  Animal
variant 122 Torso  Person  Animal
variant 32 Eye  Person  Animal
variant 26 Ear  Person  Animal
variant 55 Head  Person  Animal
variant 18 Chair 
variant 108 TV_Monitor 
variant 104 Screen  TV_Monitor 
variant 108 TV_Monitor 
variant 104 Screen  TV_Monitor 
variant 108 TV_Monitor 
variant 104 Screen  TV_Monitor 
variant 108 TV_Monitor 
variant 104 Screen  TV_Monitor 
variant 108 TV_Monitor 
variant 104 Screen  TV_Monitor 
