Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Hair  Person  Animals
Head  Person  Animals
Bus  Vehicle
Window  Bus  Vehicle
Headlight  Bus  Vehicle
Headlight  Bus  Vehicle
Mirror  Bus  Vehicle
Mirror  Bus  Vehicle
Door  Bus  Vehicle
Bodywork  Bus  Vehicle
