Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Mouth  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Head  Person  Animal
