variant 21 Dining_Table 
variant 18 Chair 
variant 18 Chair 
variant 18 Chair 
variant 108 TV_Monitor 
variant 104 Screen  TV_Monitor 
variant 12 Bottle 
variant 14 Cap  Bottle 
variant 8 Body  Bottle 
variant 12 Bottle 
variant 14 Cap  Bottle 
variant 8 Body  Bottle 
variant 12 Bottle 
variant 14 Cap  Bottle 
variant 8 Body  Bottle 
variant 12 Bottle 
variant 14 Cap  Bottle 
variant 8 Body  Bottle 
variant 12 Bottle 
variant 14 Cap  Bottle 
variant 8 Body  Bottle 
variant 12 Bottle 
variant 14 Cap  Bottle 
variant 8 Body  Bottle 
variant 12 Bottle 
variant 14 Cap  Bottle 
variant 8 Body  Bottle 
