Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Arm  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Head  Person  Animals
Chair 
Chair 
Chair 
Chair 
Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Eye  Person  Animals
Head  Person  Animals
