variant 22 Dog  Animal
variant 66 Leg  Dog  Animal
variant 66 Leg  Dog  Animal
variant 66 Leg  Dog  Animal
variant 92 Neck  Dog  Animal
variant 116 Torso  Dog  Animal
variant 94 Nose  Dog  Animal
variant 83 Muzzle  Dog  Animal
variant 27 Ear  Dog  Animal
variant 48 Head  Dog  Animal
variant 16 Cat  Animal
variant 65 Leg  Cat  Animal
variant 85 Neck  Cat  Animal
variant 117 Torso  Cat  Animal
variant 25 Ear  Cat  Animal
variant 25 Ear  Cat  Animal
variant 49 Head  Cat  Animal
