Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Mouth  Person  Animal
Ear  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Bottle 
Cap  Bottle 
Body  Bottle 
Bottle 
Cap  Bottle 
Body  Bottle 
Bottle 
Cap  Bottle 
Body  Bottle 
