Aeroplane  Vehicle
Stern  Aeroplane  Vehicle
Engine  Aeroplane  Vehicle
Engine  Aeroplane  Vehicle
Artifact_Wing  Aeroplane  Vehicle
Artifact_Wing  Aeroplane  Vehicle
Body  Aeroplane  Vehicle
Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Person  Animal
Leg  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Door  Car  Vehicle
Bodywork  Car  Vehicle
