variant 98 Person  Animal
variant 87 Neck  Person  Animal
variant 122 Torso  Person  Animal
variant 43 Hair  Person  Animal
variant 55 Head  Person  Animal
variant 98 Person  Animal
variant 87 Neck  Person  Animal
variant 122 Torso  Person  Animal
variant 55 Head  Person  Animal
variant 15 Car  Vehicle
variant 131 Window  Car  Vehicle
variant 11 Bodywork  Car  Vehicle
variant 74 License_Plate  Car  Vehicle
variant 15 Car  Vehicle
variant 131 Window  Car  Vehicle
variant 131 Window  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 78 Mirror  Car  Vehicle
variant 11 Bodywork  Car  Vehicle
variant 15 Car  Vehicle
variant 131 Window  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 59 Headlight  Car  Vehicle
variant 59 Headlight  Car  Vehicle
variant 78 Mirror  Car  Vehicle
variant 24 Door  Car  Vehicle
variant 11 Bodywork  Car  Vehicle
