Person  Animals
Foot  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Motorbike  Vehicle
Saddle  Motorbike  Vehicle
Handlebar  Motorbike  Vehicle
Headlight  Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Wheel  Motorbike  Vehicle
