variant 98 Person  Animal
variant 42 Foot  Person  Animal
variant 67 Leg  Person  Animal
variant 67 Leg  Person  Animal
variant 44 Hand  Person  Animal
variant 2 Arm  Person  Animal
variant 2 Arm  Person  Animal
variant 122 Torso  Person  Animal
variant 55 Head  Person  Animal
variant 64 Horse  Animal
variant 113 Tail  Horse  Animal
variant 71 Leg  Horse  Animal
variant 61 Hoof  Horse  Animal
variant 71 Leg  Horse  Animal
variant 61 Hoof  Horse  Animal
variant 71 Leg  Horse  Animal
variant 71 Leg  Horse  Animal
variant 93 Neck  Horse  Animal
variant 115 Torso  Horse  Animal
variant 81 Muzzle  Horse  Animal
variant 36 Eye  Horse  Animal
variant 30 Ear  Horse  Animal
variant 30 Ear  Horse  Animal
variant 51 Head  Horse  Animal
