Person  Animal
Foot  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Eyebrow  Person  Animal
Eye  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Motorbike  Vehicle
Saddle  Motorbike  Vehicle
Handlebar  Motorbike  Vehicle
Headlight  Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Wheel  Motorbike  Vehicle
