Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Hair  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Bird  Animals
Tail  Bird  Animals
Neck  Bird  Animals
Torso  Bird  Animals
Head  Bird  Animals
Bird  Animals
Tail  Bird  Animals
Neck  Bird  Animals
Torso  Bird  Animals
Head  Bird  Animals
