Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Torso  Horse  Animal
Head  Horse  Animal
Horse  Animal
Hoof  Horse  Animal
Leg  Horse  Animal
Torso  Horse  Animal
Ear  Horse  Animal
Head  Horse  Animal
