Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Head  Person  Animals
Sheep  Animals
Leg  Sheep  Animals
Leg  Sheep  Animals
Leg  Sheep  Animals
Neck  Sheep  Animals
Torso  Sheep  Animals
Muzzle  Sheep  Animals
Eye  Sheep  Animals
Ear  Sheep  Animals
Head  Sheep  Animals
