Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
