variant 98 Person  Animal
variant 42 Foot  Person  Animal
variant 67 Leg  Person  Animal
variant 42 Foot  Person  Animal
variant 67 Leg  Person  Animal
variant 44 Hand  Person  Animal
variant 122 Torso  Person  Animal
variant 15 Car  Vehicle
variant 131 Window  Car  Vehicle
variant 11 Bodywork  Car  Vehicle
variant 74 License_Plate  Car  Vehicle
variant 12 Bottle 
variant 8 Body  Bottle 
variant 12 Bottle 
variant 8 Body  Bottle 
variant 12 Bottle 
variant 14 Cap  Bottle 
variant 8 Body  Bottle 
variant 12 Bottle 
variant 8 Body  Bottle 
variant 12 Bottle 
variant 14 Cap  Bottle 
variant 8 Body  Bottle 
