Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Mouth  Person  Animal
Eyebrow  Person  Animal
Eyebrow  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Head  Person  Animal
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Mouth  Person  Animal
Eyebrow  Person  Animal
Eyebrow  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Head  Person  Animal
Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Wheel  Motorbike  Vehicle
