variant 22 Dog  Animal
variant 110 Tail  Dog  Animal
variant 66 Leg  Dog  Animal
variant 66 Leg  Dog  Animal
variant 66 Leg  Dog  Animal
variant 92 Neck  Dog  Animal
variant 116 Torso  Dog  Animal
variant 48 Head  Dog  Animal
variant 15 Car  Vehicle
variant 131 Window  Car  Vehicle
variant 131 Window  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 78 Mirror  Car  Vehicle
variant 11 Bodywork  Car  Vehicle
