variant 98 Person  Animal
variant 87 Neck  Person  Animal
variant 122 Torso  Person  Animal
variant 95 Nose  Person  Animal
variant 80 Mouth  Person  Animal
variant 26 Ear  Person  Animal
variant 55 Head  Person  Animal
variant 6 Bird  Animal
variant 112 Tail  Bird  Animal
variant 68 Leg  Bird  Animal
variant 121 Torso  Bird  Animal
variant 4 Beak  Bird  Animal
variant 35 Eye  Bird  Animal
variant 47 Head  Bird  Animal
