variant 101 Potted_Plant 
variant 99 Plant  Potted_Plant 
variant 100 Pot  Potted_Plant 
variant 13 Bus  Vehicle
variant 130 Window  Bus  Vehicle
variant 130 Window  Bus  Vehicle
variant 10 Bodywork  Bus  Vehicle
variant 5 Bicycle  Vehicle
variant 103 Saddle  Bicycle  Vehicle
variant 46 Handlebar  Bicycle  Vehicle
variant 17 Chain_Wheel  Bicycle  Vehicle
variant 128 Wheel  Bicycle  Vehicle
variant 128 Wheel  Bicycle  Vehicle
