Car  Vehicle
Headlight  Car  Vehicle
Headlight  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
Car  Vehicle
Window  Car  Vehicle
Headlight  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Mirror  Car  Vehicle
Bodywork  Car  Vehicle
Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Wheel  Bus  Vehicle
Bodywork  Bus  Vehicle
