Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Mouth  Person  Animal
Eyebrow  Person  Animal
Eyebrow  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Head  Person  Animal
Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Mouth  Person  Animal
Eyebrow  Person  Animal
Eyebrow  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Cat  Animal
Tail  Cat  Animal
Leg  Cat  Animal
Leg  Cat  Animal
Leg  Cat  Animal
Neck  Cat  Animal
Torso  Cat  Animal
Ear  Cat  Animal
Head  Cat  Animal
