Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Hair  Person  Animals
Head  Person  Animals
Cow  Animals
Leg  Cow  Animals
Leg  Cow  Animals
Leg  Cow  Animals
Leg  Cow  Animals
Neck  Cow  Animals
Torso  Cow  Animals
Muzzle  Cow  Animals
Horn  Cow  Animals
Ear  Cow  Animals
Ear  Cow  Animals
Head  Cow  Animals
