variant 101 Potted_Plant 
variant 99 Plant  Potted_Plant 
variant 100 Pot  Potted_Plant 
variant 101 Potted_Plant 
variant 99 Plant  Potted_Plant 
variant 100 Pot  Potted_Plant 
variant 101 Potted_Plant 
variant 99 Plant  Potted_Plant 
variant 100 Pot  Potted_Plant 
variant 101 Potted_Plant 
variant 99 Plant  Potted_Plant 
variant 100 Pot  Potted_Plant 
variant 101 Potted_Plant 
variant 99 Plant  Potted_Plant 
variant 100 Pot  Potted_Plant 
variant 0 Aeroplane  Vehicle
variant 107 Stern  Aeroplane  Vehicle
variant 127 Wheel  Aeroplane  Vehicle
variant 127 Wheel  Aeroplane  Vehicle
variant 127 Wheel  Aeroplane  Vehicle
variant 3 Artifact_Wing  Aeroplane  Vehicle
variant 9 Body  Aeroplane  Vehicle
