variant 98 Person  Animal
variant 42 Foot  Person  Animal
variant 67 Leg  Person  Animal
variant 42 Foot  Person  Animal
variant 67 Leg  Person  Animal
variant 44 Hand  Person  Animal
variant 2 Arm  Person  Animal
variant 87 Neck  Person  Animal
variant 122 Torso  Person  Animal
variant 43 Hair  Person  Animal
variant 55 Head  Person  Animal
variant 20 Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 91 Neck  Cow  Animal
variant 118 Torso  Cow  Animal
variant 84 Muzzle  Cow  Animal
variant 63 Horn  Cow  Animal
variant 28 Ear  Cow  Animal
variant 28 Ear  Cow  Animal
variant 50 Head  Cow  Animal
