Person  Animals
Leg  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Mouth  Person  Animals
Eyebrow  Person  Animals
Eyebrow  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Train  Vehicle
Locomotive  Train  Vehicle
Coach  Train  Vehicle
Coach  Train  Vehicle
