variant 98 Person  Animal
variant 42 Foot  Person  Animal
variant 67 Leg  Person  Animal
variant 42 Foot  Person  Animal
variant 67 Leg  Person  Animal
variant 2 Arm  Person  Animal
variant 122 Torso  Person  Animal
variant 95 Nose  Person  Animal
variant 80 Mouth  Person  Animal
variant 41 Eyebrow  Person  Animal
variant 41 Eyebrow  Person  Animal
variant 32 Eye  Person  Animal
variant 32 Eye  Person  Animal
variant 26 Ear  Person  Animal
variant 26 Ear  Person  Animal
variant 55 Head  Person  Animal
variant 124 Train  Vehicle
variant 19 Coach  Train  Vehicle
variant 19 Coach  Train  Vehicle
variant 19 Coach  Train  Vehicle
