variant 21 Dining_Table 
variant 106 Sofa 
variant 106 Sofa 
variant 106 Sofa 
variant 98 Person  Animal
variant 122 Torso  Person  Animal
variant 95 Nose  Person  Animal
variant 43 Hair  Person  Animal
variant 80 Mouth  Person  Animal
variant 41 Eyebrow  Person  Animal
variant 41 Eyebrow  Person  Animal
variant 32 Eye  Person  Animal
variant 32 Eye  Person  Animal
variant 55 Head  Person  Animal
variant 18 Chair 
variant 18 Chair 
variant 18 Chair 
variant 18 Chair 
variant 108 TV_Monitor 
variant 104 Screen  TV_Monitor 
