Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Person  Animal
Leg  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Person  Animal
Head  Person  Animal
Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Mirror  Car  Vehicle
Mirror  Car  Vehicle
Bodywork  Car  Vehicle
