Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Motorbike  Vehicle
Headlight  Motorbike  Vehicle
Headlight  Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Motorbike  Vehicle
Headlight  Motorbike  Vehicle
Headlight  Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Headlight  Car  Vehicle
Headlight  Car  Vehicle
Mirror  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
