Person  Animals
Torso  Person  Animals
Head  Person  Animals
Person  Animals
Torso  Person  Animals
Head  Person  Animals
Train  Vehicle
Locomotive  Train  Vehicle
Headlight  Train  Vehicle
Headlight  Train  Vehicle
Coach  Train  Vehicle
Coach  Train  Vehicle
Coach  Train  Vehicle
Coach  Train  Vehicle
Coach  Train  Vehicle
Coach  Train  Vehicle
Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
