Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Mouth  Person  Animal
Eye  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Cow  Animal
Torso  Cow  Animal
Muzzle  Cow  Animal
Eye  Cow  Animal
Ear  Cow  Animal
Head  Cow  Animal
Cow  Animal
Torso  Cow  Animal
Muzzle  Cow  Animal
Eye  Cow  Animal
Eye  Cow  Animal
Ear  Cow  Animal
Ear  Cow  Animal
Head  Cow  Animal
