Person  Animal
Torso  Person  Animal
Head  Person  Animal
Person  Animal
Torso  Person  Animal
Head  Person  Animal
Train  Vehicle
Locomotive  Train  Vehicle
Headlight  Train  Vehicle
Headlight  Train  Vehicle
Coach  Train  Vehicle
Coach  Train  Vehicle
Coach  Train  Vehicle
Coach  Train  Vehicle
Coach  Train  Vehicle
Coach  Train  Vehicle
Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
