variant 98 Person  Animal
variant 67 Leg  Person  Animal
variant 67 Leg  Person  Animal
variant 2 Arm  Person  Animal
variant 122 Torso  Person  Animal
variant 43 Hair  Person  Animal
variant 55 Head  Person  Animal
variant 98 Person  Animal
variant 67 Leg  Person  Animal
variant 2 Arm  Person  Animal
variant 2 Arm  Person  Animal
variant 122 Torso  Person  Animal
variant 43 Hair  Person  Animal
variant 55 Head  Person  Animal
variant 15 Car  Vehicle
variant 13 Bus  Vehicle
variant 130 Window  Bus  Vehicle
variant 130 Window  Bus  Vehicle
variant 126 Wheel  Bus  Vehicle
variant 126 Wheel  Bus  Vehicle
variant 77 Mirror  Bus  Vehicle
variant 77 Mirror  Bus  Vehicle
variant 23 Door  Bus  Vehicle
variant 23 Door  Bus  Vehicle
variant 10 Bodywork  Bus  Vehicle
