Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Head  Person  Animal
Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Head  Person  Animal
Car  Vehicle
Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Wheel  Bus  Vehicle
Wheel  Bus  Vehicle
Mirror  Bus  Vehicle
Mirror  Bus  Vehicle
Door  Bus  Vehicle
Door  Bus  Vehicle
Bodywork  Bus  Vehicle
