Person  Animals
Arm  Person  Animals
Hair  Person  Animals
Head  Person  Animals
Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Eye  Person  Animals
Head  Person  Animals
Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Head  Person  Animals
Car  Vehicle
Wheel  Car  Vehicle
Bodywork  Car  Vehicle
Car  Vehicle
Window  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Bodywork  Car  Vehicle
Car  Vehicle
Car  Vehicle
Car  Vehicle
Car  Vehicle
Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Wheel  Bus  Vehicle
Wheel  Bus  Vehicle
Headlight  Bus  Vehicle
Headlight  Bus  Vehicle
Mirror  Bus  Vehicle
Mirror  Bus  Vehicle
Door  Bus  Vehicle
Bodywork  Bus  Vehicle
License_Plate  Bus  Vehicle
