Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Head  Person  Animal
Cow  Animal
Muzzle  Cow  Animal
Eye  Cow  Animal
Head  Cow  Animal
Cow  Animal
Torso  Cow  Animal
Muzzle  Cow  Animal
Eye  Cow  Animal
Head  Cow  Animal
Cow  Animal
Leg  Cow  Animal
Neck  Cow  Animal
Torso  Cow  Animal
Muzzle  Cow  Animal
Eye  Cow  Animal
Ear  Cow  Animal
Head  Cow  Animal
