Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Torso  Dog  Animals
Ear  Dog  Animals
Ear  Dog  Animals
Head  Dog  Animals
Bicycle  Vehicle
Saddle  Bicycle  Vehicle
Handlebar  Bicycle  Vehicle
Chain_Wheel  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
