Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Person  Animals
Torso  Person  Animals
Hair  Person  Animals
Head  Person  Animals
Person  Animals
Hair  Person  Animals
Ear  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Hair  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Person  Animals
Hair  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Person  Animals
Hair  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Aeroplane  Vehicle
Stern  Aeroplane  Vehicle
Artifact_Wing  Aeroplane  Vehicle
Artifact_Wing  Aeroplane  Vehicle
Body  Aeroplane  Vehicle
Aeroplane  Vehicle
Artifact_Wing  Aeroplane  Vehicle
Artifact_Wing  Aeroplane  Vehicle
Body  Aeroplane  Vehicle
Aeroplane  Vehicle
Stern  Aeroplane  Vehicle
Artifact_Wing  Aeroplane  Vehicle
Artifact_Wing  Aeroplane  Vehicle
Body  Aeroplane  Vehicle
