Dining_Table 
Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Sofa 
Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Mouth  Person  Animals
Eye  Person  Animals
Head  Person  Animals
Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Head  Person  Animals
Chair 
Chair 
Chair 
Chair 
Chair 
Dog  Animals
Tail  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Neck  Dog  Animals
Torso  Dog  Animals
Eye  Dog  Animals
Head  Dog  Animals
Dog  Animals
Torso  Dog  Animals
Eye  Dog  Animals
Eye  Dog  Animals
Head  Dog  Animals
Bottle 
Cap  Bottle 
Body  Bottle 
