Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Head  Person  Animals
Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Mirror  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Mirror  Car  Vehicle
Door  Car  Vehicle
Door  Car  Vehicle
Bodywork  Car  Vehicle
