Dining_Table 
Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Sofa 
Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Mouth  Person  Animal
Eye  Person  Animal
Head  Person  Animal
Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Eyebrow  Person  Animal
Eye  Person  Animal
Head  Person  Animal
Chair 
Chair 
Chair 
Chair 
Chair 
Dog  Animal
Tail  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Neck  Dog  Animal
Torso  Dog  Animal
Eye  Dog  Animal
Head  Dog  Animal
Dog  Animal
Torso  Dog  Animal
Eye  Dog  Animal
Eye  Dog  Animal
Head  Dog  Animal
Bottle 
Cap  Bottle 
Body  Bottle 
