variant 124 Train  Vehicle
variant 76 Locomotive  Train  Vehicle
variant 60 Headlight  Train  Vehicle
variant 98 Person  Animal
variant 42 Foot  Person  Animal
variant 67 Leg  Person  Animal
variant 42 Foot  Person  Animal
variant 67 Leg  Person  Animal
variant 2 Arm  Person  Animal
variant 2 Arm  Person  Animal
variant 87 Neck  Person  Animal
variant 122 Torso  Person  Animal
variant 55 Head  Person  Animal
variant 124 Train  Vehicle
variant 19 Coach  Train  Vehicle
variant 124 Train  Vehicle
variant 76 Locomotive  Train  Vehicle
