Bicycle  Vehicle
Chain_Wheel  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Motorbike  Vehicle
Headlight  Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Wheel  Motorbike  Vehicle
