Person  Animals
Leg  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Sheep  Animals
Tail  Sheep  Animals
Neck  Sheep  Animals
Torso  Sheep  Animals
Eye  Sheep  Animals
Ear  Sheep  Animals
Ear  Sheep  Animals
Head  Sheep  Animals
Sheep  Animals
Tail  Sheep  Animals
Neck  Sheep  Animals
Torso  Sheep  Animals
Muzzle  Sheep  Animals
Ear  Sheep  Animals
Ear  Sheep  Animals
Head  Sheep  Animals
Sheep  Animals
Tail  Sheep  Animals
Neck  Sheep  Animals
Torso  Sheep  Animals
Ear  Sheep  Animals
Ear  Sheep  Animals
Head  Sheep  Animals
