Aeroplane  Vehicle
Stern  Aeroplane  Vehicle
Body  Aeroplane  Vehicle
Aeroplane  Vehicle
Stern  Aeroplane  Vehicle
Artifact_Wing  Aeroplane  Vehicle
Body  Aeroplane  Vehicle
Aeroplane  Vehicle
Stern  Aeroplane  Vehicle
Wheel  Aeroplane  Vehicle
Wheel  Aeroplane  Vehicle
Wheel  Aeroplane  Vehicle
Engine  Aeroplane  Vehicle
Artifact_Wing  Aeroplane  Vehicle
Body  Aeroplane  Vehicle
Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Torso  Person  Animals
