variant 64 Horse  Animal
variant 71 Leg  Horse  Animal
variant 71 Leg  Horse  Animal
variant 71 Leg  Horse  Animal
variant 93 Neck  Horse  Animal
variant 115 Torso  Horse  Animal
variant 81 Muzzle  Horse  Animal
variant 36 Eye  Horse  Animal
variant 30 Ear  Horse  Animal
variant 51 Head  Horse  Animal
variant 22 Dog  Animal
variant 92 Neck  Dog  Animal
variant 116 Torso  Dog  Animal
variant 94 Nose  Dog  Animal
variant 83 Muzzle  Dog  Animal
variant 34 Eye  Dog  Animal
variant 27 Ear  Dog  Animal
variant 48 Head  Dog  Animal
