Bicycle  Vehicle
Saddle  Bicycle  Vehicle
Handlebar  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
Person  Animals
Leg  Person  Animals
Torso  Person  Animals
Head  Person  Animals
Person  Animals
Arm  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Head  Person  Animals
Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Bodywork  Car  Vehicle
Bus  Vehicle
