Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Head  Person  Animals
Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Mirror  Car  Vehicle
Bodywork  Car  Vehicle
Bus  Vehicle
Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Wheel  Bus  Vehicle
Wheel  Bus  Vehicle
Wheel  Bus  Vehicle
Headlight  Bus  Vehicle
Headlight  Bus  Vehicle
Mirror  Bus  Vehicle
Bodywork  Bus  Vehicle
License_Plate  Bus  Vehicle
Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Wheel  Bus  Vehicle
Wheel  Bus  Vehicle
Wheel  Bus  Vehicle
Headlight  Bus  Vehicle
Headlight  Bus  Vehicle
Mirror  Bus  Vehicle
Mirror  Bus  Vehicle
Door  Bus  Vehicle
Door  Bus  Vehicle
Door  Bus  Vehicle
Bodywork  Bus  Vehicle
License_Plate  Bus  Vehicle
Bicycle  Vehicle
Handlebar  Bicycle  Vehicle
Chain_Wheel  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
