variant 15 Car  Vehicle
variant 131 Window  Car  Vehicle
variant 131 Window  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 59 Headlight  Car  Vehicle
variant 59 Headlight  Car  Vehicle
variant 24 Door  Car  Vehicle
variant 24 Door  Car  Vehicle
variant 11 Bodywork  Car  Vehicle
variant 74 License_Plate  Car  Vehicle
variant 16 Cat  Animal
variant 111 Tail  Cat  Animal
variant 65 Leg  Cat  Animal
variant 65 Leg  Cat  Animal
variant 85 Neck  Cat  Animal
variant 117 Torso  Cat  Animal
variant 49 Head  Cat  Animal
variant 33 Eye  Cat  Animal
variant 33 Eye  Cat  Animal
variant 25 Ear  Cat  Animal
variant 25 Ear  Cat  Animal
