Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Headlight  Car  Vehicle
Headlight  Car  Vehicle
Door  Car  Vehicle
Door  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
Cat  Animals
Tail  Cat  Animals
Leg  Cat  Animals
Leg  Cat  Animals
Neck  Cat  Animals
Torso  Cat  Animals
Head  Cat  Animals
Eye  Cat  Animals
Eye  Cat  Animals
Ear  Cat  Animals
Ear  Cat  Animals
