Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Headlight  Car  Vehicle
Headlight  Car  Vehicle
Door  Car  Vehicle
Door  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
Cat  Animal
Tail  Cat  Animal
Leg  Cat  Animal
Leg  Cat  Animal
Neck  Cat  Animal
Torso  Cat  Animal
Head  Cat  Animal
Eye  Cat  Animal
Eye  Cat  Animal
Ear  Cat  Animal
Ear  Cat  Animal
