variant 98 Person  Animal
variant 42 Foot  Person  Animal
variant 67 Leg  Person  Animal
variant 42 Foot  Person  Animal
variant 67 Leg  Person  Animal
variant 122 Torso  Person  Animal
variant 55 Head  Person  Animal
variant 7 Boat  Vehicle
variant 15 Car  Vehicle
variant 131 Window  Car  Vehicle
variant 131 Window  Car  Vehicle
variant 131 Window  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 59 Headlight  Car  Vehicle
variant 59 Headlight  Car  Vehicle
variant 78 Mirror  Car  Vehicle
variant 24 Door  Car  Vehicle
variant 24 Door  Car  Vehicle
variant 11 Bodywork  Car  Vehicle
variant 74 License_Plate  Car  Vehicle
variant 15 Car  Vehicle
variant 131 Window  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 11 Bodywork  Car  Vehicle
variant 15 Car  Vehicle
variant 131 Window  Car  Vehicle
variant 11 Bodywork  Car  Vehicle
