variant 98 Person  Animal
variant 44 Hand  Person  Animal
variant 44 Hand  Person  Animal
variant 122 Torso  Person  Animal
variant 98 Person  Animal
variant 44 Hand  Person  Animal
variant 2 Arm  Person  Animal
variant 44 Hand  Person  Animal
variant 2 Arm  Person  Animal
variant 122 Torso  Person  Animal
variant 18 Chair 
variant 18 Chair 
variant 18 Chair 
variant 18 Chair 
variant 18 Chair 
variant 18 Chair 
variant 21 Dining_Table 
