Sofa 
Sofa 
Sofa 
Sofa 
Chair 
Chair 
Chair 
Chair 
Person  Animals
Leg  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Mouth  Person  Animals
Eyebrow  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Head  Person  Animals
Dog  Animals
Tail  Dog  Animals
Leg  Dog  Animals
Neck  Dog  Animals
Torso  Dog  Animals
Ear  Dog  Animals
Ear  Dog  Animals
Head  Dog  Animals
