variant 21 Dining_Table 
variant 21 Dining_Table 
variant 98 Person  Animal
variant 87 Neck  Person  Animal
variant 122 Torso  Person  Animal
variant 55 Head  Person  Animal
variant 18 Chair 
variant 18 Chair 
variant 18 Chair 
variant 18 Chair 
variant 18 Chair 
variant 18 Chair 
variant 18 Chair 
variant 21 Dining_Table 
variant 21 Dining_Table 
variant 21 Dining_Table 
variant 21 Dining_Table 
variant 18 Chair 
variant 18 Chair 
variant 18 Chair 
variant 18 Chair 
variant 21 Dining_Table 
variant 18 Chair 
variant 18 Chair 
variant 21 Dining_Table 
