Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Head  Person  Animals
Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Head  Person  Animals
Motorbike  Vehicle
Headlight  Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Motorbike  Vehicle
Headlight  Motorbike  Vehicle
Headlight  Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Bodywork  Car  Vehicle
