Person  Animal
Torso  Person  Animal
Head  Person  Animal
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Mouth  Person  Animal
Head  Person  Animal
Horse  Animal
Tail  Horse  Animal
Leg  Horse  Animal
Horse  Animal
Tail  Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Hoof  Horse  Animal
Leg  Horse  Animal
Hoof  Horse  Animal
Leg  Horse  Animal
Torso  Horse  Animal
Ear  Horse  Animal
Head  Horse  Animal
