Person  Animals
Torso  Person  Animals
Head  Person  Animals
Aeroplane  Vehicle
Stern  Aeroplane  Vehicle
Wheel  Aeroplane  Vehicle
Wheel  Aeroplane  Vehicle
Wheel  Aeroplane  Vehicle
Engine  Aeroplane  Vehicle
Artifact_Wing  Aeroplane  Vehicle
Body  Aeroplane  Vehicle
Aeroplane  Vehicle
Wheel  Aeroplane  Vehicle
Engine  Aeroplane  Vehicle
Engine  Aeroplane  Vehicle
Artifact_Wing  Aeroplane  Vehicle
Body  Aeroplane  Vehicle
