Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Arm  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Head  Person  Animals
Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Head  Person  Animals
Person  Animals
Leg  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Person  Animals
Leg  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Dining_Table 
Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Door  Car  Vehicle
Door  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
Bottle 
Cap  Bottle 
Body  Bottle 
