Horse  Animal
Tail  Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Neck  Horse  Animal
Torso  Horse  Animal
Muzzle  Horse  Animal
Head  Horse  Animal
Horse  Animal
Tail  Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Neck  Horse  Animal
Torso  Horse  Animal
Muzzle  Horse  Animal
Ear  Horse  Animal
Ear  Horse  Animal
Head  Horse  Animal
