variant 98 Person  Animal
variant 122 Torso  Person  Animal
variant 95 Nose  Person  Animal
variant 43 Hair  Person  Animal
variant 55 Head  Person  Animal
variant 98 Person  Animal
variant 122 Torso  Person  Animal
variant 95 Nose  Person  Animal
variant 43 Hair  Person  Animal
variant 55 Head  Person  Animal
variant 108 TV_Monitor 
variant 104 Screen  TV_Monitor 
variant 108 TV_Monitor 
variant 104 Screen  TV_Monitor 
variant 12 Bottle 
variant 14 Cap  Bottle 
variant 8 Body  Bottle 
