Sheep  Animal
Torso  Sheep  Animal
Ear  Sheep  Animal
Ear  Sheep  Animal
Head  Sheep  Animal
Sheep  Animal
Neck  Sheep  Animal
Torso  Sheep  Animal
Ear  Sheep  Animal
Ear  Sheep  Animal
Head  Sheep  Animal
Sheep  Animal
Neck  Sheep  Animal
Torso  Sheep  Animal
Muzzle  Sheep  Animal
Eye  Sheep  Animal
Ear  Sheep  Animal
Head  Sheep  Animal
Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Torso  Dog  Animal
Nose  Dog  Animal
Muzzle  Dog  Animal
Ear  Dog  Animal
Head  Dog  Animal
