variant 16 Cat  Animal
variant 65 Leg  Cat  Animal
variant 65 Leg  Cat  Animal
variant 85 Neck  Cat  Animal
variant 117 Torso  Cat  Animal
variant 49 Head  Cat  Animal
variant 33 Eye  Cat  Animal
variant 33 Eye  Cat  Animal
variant 25 Ear  Cat  Animal
variant 25 Ear  Cat  Animal
variant 105 Sheep  Animal
variant 86 Neck  Sheep  Animal
variant 123 Torso  Sheep  Animal
variant 82 Muzzle  Sheep  Animal
variant 37 Eye  Sheep  Animal
variant 29 Ear  Sheep  Animal
variant 54 Head  Sheep  Animal
