Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Mouth  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Dining_Table 
Chair 
Chair 
Chair 
