Dog  Animals
Tail  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Torso  Dog  Animals
Nose  Dog  Animals
Muzzle  Dog  Animals
Eye  Dog  Animals
Ear  Dog  Animals
Ear  Dog  Animals
Head  Dog  Animals
Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
