variant 106 Sofa 
variant 106 Sofa 
variant 98 Person  Animal
variant 122 Torso  Person  Animal
variant 55 Head  Person  Animal
variant 98 Person  Animal
variant 87 Neck  Person  Animal
variant 122 Torso  Person  Animal
variant 55 Head  Person  Animal
variant 108 TV_Monitor 
variant 104 Screen  TV_Monitor 
variant 18 Chair 
variant 108 TV_Monitor 
variant 104 Screen  TV_Monitor 
variant 108 TV_Monitor 
variant 104 Screen  TV_Monitor 
