variant 98 Person  Animal
variant 42 Foot  Person  Animal
variant 98 Person  Animal
variant 42 Foot  Person  Animal
variant 98 Person  Animal
variant 42 Foot  Person  Animal
variant 67 Leg  Person  Animal
variant 42 Foot  Person  Animal
variant 67 Leg  Person  Animal
variant 5 Bicycle  Vehicle
variant 46 Handlebar  Bicycle  Vehicle
variant 17 Chain_Wheel  Bicycle  Vehicle
variant 128 Wheel  Bicycle  Vehicle
variant 128 Wheel  Bicycle  Vehicle
