Sheep  Animals
Neck  Sheep  Animals
Torso  Sheep  Animals
Muzzle  Sheep  Animals
Eye  Sheep  Animals
Ear  Sheep  Animals
Ear  Sheep  Animals
Head  Sheep  Animals
Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Headlight  Car  Vehicle
Headlight  Car  Vehicle
Mirror  Car  Vehicle
Mirror  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
Sheep  Animals
Neck  Sheep  Animals
Torso  Sheep  Animals
Muzzle  Sheep  Animals
Horn  Sheep  Animals
Horn  Sheep  Animals
Eye  Sheep  Animals
Ear  Sheep  Animals
Head  Sheep  Animals
