Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Mouth  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Mouth  Person  Animals
Eyebrow  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Head  Person  Animals
Train  Vehicle
Locomotive  Train  Vehicle
Headlight  Train  Vehicle
Headlight  Train  Vehicle
Headlight  Train  Vehicle
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
