variant 105 Sheep  Animal
variant 86 Neck  Sheep  Animal
variant 123 Torso  Sheep  Animal
variant 82 Muzzle  Sheep  Animal
variant 37 Eye  Sheep  Animal
variant 29 Ear  Sheep  Animal
variant 29 Ear  Sheep  Animal
variant 54 Head  Sheep  Animal
variant 15 Car  Vehicle
variant 131 Window  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 59 Headlight  Car  Vehicle
variant 59 Headlight  Car  Vehicle
variant 78 Mirror  Car  Vehicle
variant 78 Mirror  Car  Vehicle
variant 11 Bodywork  Car  Vehicle
variant 74 License_Plate  Car  Vehicle
variant 105 Sheep  Animal
variant 86 Neck  Sheep  Animal
variant 123 Torso  Sheep  Animal
variant 82 Muzzle  Sheep  Animal
variant 62 Horn  Sheep  Animal
variant 62 Horn  Sheep  Animal
variant 37 Eye  Sheep  Animal
variant 29 Ear  Sheep  Animal
variant 54 Head  Sheep  Animal
