Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Mouth  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Mouth  Person  Animal
Eyebrow  Person  Animal
Eyebrow  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Head  Person  Animal
Train  Vehicle
Locomotive  Train  Vehicle
Headlight  Train  Vehicle
Headlight  Train  Vehicle
Headlight  Train  Vehicle
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
