variant 98 Person  Animal
variant 44 Hand  Person  Animal
variant 2 Arm  Person  Animal
variant 2 Arm  Person  Animal
variant 122 Torso  Person  Animal
variant 21 Dining_Table 
variant 12 Bottle 
variant 8 Body  Bottle 
variant 12 Bottle 
variant 14 Cap  Bottle 
variant 8 Body  Bottle 
variant 12 Bottle 
variant 14 Cap  Bottle 
variant 8 Body  Bottle 
variant 12 Bottle 
variant 14 Cap  Bottle 
variant 8 Body  Bottle 
