Sheep  Animal
Neck  Sheep  Animal
Torso  Sheep  Animal
Muzzle  Sheep  Animal
Eye  Sheep  Animal
Ear  Sheep  Animal
Ear  Sheep  Animal
Head  Sheep  Animal
Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Headlight  Car  Vehicle
Headlight  Car  Vehicle
Mirror  Car  Vehicle
Mirror  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
Sheep  Animal
Neck  Sheep  Animal
Torso  Sheep  Animal
Muzzle  Sheep  Animal
Horn  Sheep  Animal
Horn  Sheep  Animal
Eye  Sheep  Animal
Ear  Sheep  Animal
Head  Sheep  Animal
