Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Person  Animals
Hand  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Eyebrow  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Head  Person  Animals
Cat  Animals
Tail  Cat  Animals
Leg  Cat  Animals
Leg  Cat  Animals
Leg  Cat  Animals
Neck  Cat  Animals
Torso  Cat  Animals
Head  Cat  Animals
Eye  Cat  Animals
Eye  Cat  Animals
Ear  Cat  Animals
Ear  Cat  Animals
