variant 124 Train  Vehicle
variant 76 Locomotive  Train  Vehicle
variant 60 Headlight  Train  Vehicle
variant 60 Headlight  Train  Vehicle
variant 19 Coach  Train  Vehicle
variant 19 Coach  Train  Vehicle
variant 98 Person  Animal
variant 122 Torso  Person  Animal
variant 95 Nose  Person  Animal
variant 80 Mouth  Person  Animal
variant 32 Eye  Person  Animal
variant 32 Eye  Person  Animal
variant 55 Head  Person  Animal
