variant 98 Person  Animal
variant 42 Foot  Person  Animal
variant 67 Leg  Person  Animal
variant 67 Leg  Person  Animal
variant 44 Hand  Person  Animal
variant 2 Arm  Person  Animal
variant 44 Hand  Person  Animal
variant 2 Arm  Person  Animal
variant 122 Torso  Person  Animal
variant 43 Hair  Person  Animal
variant 26 Ear  Person  Animal
variant 55 Head  Person  Animal
variant 101 Potted_Plant 
variant 99 Plant  Potted_Plant 
variant 100 Pot  Potted_Plant 
