Bird  Animals
Tail  Bird  Animals
Leg  Bird  Animals
Leg  Bird  Animals
Animal_Wing  Bird  Animals
Animal_Wing  Bird  Animals
Torso  Bird  Animals
Beak  Bird  Animals
Eye  Bird  Animals
Eye  Bird  Animals
Head  Bird  Animals
Bird  Animals
Tail  Bird  Animals
Leg  Bird  Animals
Leg  Bird  Animals
Animal_Wing  Bird  Animals
Animal_Wing  Bird  Animals
Torso  Bird  Animals
Beak  Bird  Animals
Eye  Bird  Animals
Eye  Bird  Animals
Head  Bird  Animals
