Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Train  Vehicle
Locomotive  Train  Vehicle
Headlight  Train  Vehicle
Headlight  Train  Vehicle
Coach  Train  Vehicle
Coach  Train  Vehicle
Coach  Train  Vehicle
Coach  Train  Vehicle
Coach  Train  Vehicle
Coach  Train  Vehicle
