Aeroplane  Vehicle
Stern  Aeroplane  Vehicle
Wheel  Aeroplane  Vehicle
Wheel  Aeroplane  Vehicle
Wheel  Aeroplane  Vehicle
Artifact_Wing  Aeroplane  Vehicle
Body  Aeroplane  Vehicle
Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Mouth  Person  Animal
Eye  Person  Animal
Head  Person  Animal
Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Mouth  Person  Animal
Eye  Person  Animal
Head  Person  Animal
