variant 0 Aeroplane  Vehicle
variant 107 Stern  Aeroplane  Vehicle
variant 127 Wheel  Aeroplane  Vehicle
variant 127 Wheel  Aeroplane  Vehicle
variant 127 Wheel  Aeroplane  Vehicle
variant 3 Artifact_Wing  Aeroplane  Vehicle
variant 9 Body  Aeroplane  Vehicle
variant 98 Person  Animal
variant 122 Torso  Person  Animal
variant 95 Nose  Person  Animal
variant 80 Mouth  Person  Animal
variant 32 Eye  Person  Animal
variant 55 Head  Person  Animal
variant 98 Person  Animal
variant 122 Torso  Person  Animal
variant 95 Nose  Person  Animal
variant 80 Mouth  Person  Animal
variant 32 Eye  Person  Animal
variant 55 Head  Person  Animal
