variant 98 Person  Animal
variant 67 Leg  Person  Animal
variant 67 Leg  Person  Animal
variant 2 Arm  Person  Animal
variant 2 Arm  Person  Animal
variant 122 Torso  Person  Animal
variant 55 Head  Person  Animal
variant 98 Person  Animal
variant 67 Leg  Person  Animal
variant 67 Leg  Person  Animal
variant 122 Torso  Person  Animal
variant 55 Head  Person  Animal
variant 5 Bicycle  Vehicle
variant 103 Saddle  Bicycle  Vehicle
variant 17 Chain_Wheel  Bicycle  Vehicle
variant 128 Wheel  Bicycle  Vehicle
variant 128 Wheel  Bicycle  Vehicle
