Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Mirror  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Mirror  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
Aeroplane  Vehicle
Stern  Aeroplane  Vehicle
Wheel  Aeroplane  Vehicle
Wheel  Aeroplane  Vehicle
Wheel  Aeroplane  Vehicle
Artifact_Wing  Aeroplane  Vehicle
Artifact_Wing  Aeroplane  Vehicle
Body  Aeroplane  Vehicle
