variant 98 Person  Animal
variant 67 Leg  Person  Animal
variant 122 Torso  Person  Animal
variant 95 Nose  Person  Animal
variant 43 Hair  Person  Animal
variant 32 Eye  Person  Animal
variant 26 Ear  Person  Animal
variant 55 Head  Person  Animal
variant 18 Chair 
variant 18 Chair 
variant 18 Chair 
variant 101 Potted_Plant 
variant 99 Plant  Potted_Plant 
variant 100 Pot  Potted_Plant 
variant 101 Potted_Plant 
variant 99 Plant  Potted_Plant 
variant 100 Pot  Potted_Plant 
variant 101 Potted_Plant 
variant 99 Plant  Potted_Plant 
variant 100 Pot  Potted_Plant 
variant 101 Potted_Plant 
variant 99 Plant  Potted_Plant 
variant 100 Pot  Potted_Plant 
