Person  Animals
Leg  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Eye  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Chair 
Chair 
Chair 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
