Person  Animals
Nose  Person  Animals
Mouth  Person  Animals
Eyebrow  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Head  Person  Animals
Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Muzzle  Dog  Animals
Eye  Dog  Animals
Ear  Dog  Animals
Head  Dog  Animals
