variant 0 Aeroplane  Vehicle
variant 127 Wheel  Aeroplane  Vehicle
variant 31 Engine  Aeroplane  Vehicle
variant 31 Engine  Aeroplane  Vehicle
variant 3 Artifact_Wing  Aeroplane  Vehicle
variant 9 Body  Aeroplane  Vehicle
variant 98 Person  Animal
variant 42 Foot  Person  Animal
variant 67 Leg  Person  Animal
variant 42 Foot  Person  Animal
variant 67 Leg  Person  Animal
variant 44 Hand  Person  Animal
variant 2 Arm  Person  Animal
variant 44 Hand  Person  Animal
variant 2 Arm  Person  Animal
variant 122 Torso  Person  Animal
variant 95 Nose  Person  Animal
variant 43 Hair  Person  Animal
variant 80 Mouth  Person  Animal
variant 41 Eyebrow  Person  Animal
variant 41 Eyebrow  Person  Animal
variant 32 Eye  Person  Animal
variant 32 Eye  Person  Animal
variant 26 Ear  Person  Animal
variant 26 Ear  Person  Animal
variant 55 Head  Person  Animal
