Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Head  Person  Animals
Person  Animals
Leg  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Head  Person  Animals
Train  Vehicle
Coach  Train  Vehicle
Locomotive  Train  Vehicle
Headlight  Train  Vehicle
Coach  Train  Vehicle
Coach  Train  Vehicle
Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Bodywork  Car  Vehicle
