Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Aeroplane  Vehicle
Stern  Aeroplane  Vehicle
Artifact_Wing  Aeroplane  Vehicle
Body  Aeroplane  Vehicle
Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Head  Person  Animal
