variant 101 Potted_Plant 
variant 99 Plant  Potted_Plant 
variant 100 Pot  Potted_Plant 
variant 101 Potted_Plant 
variant 99 Plant  Potted_Plant 
variant 100 Pot  Potted_Plant 
variant 101 Potted_Plant 
variant 99 Plant  Potted_Plant 
variant 100 Pot  Potted_Plant 
variant 101 Potted_Plant 
variant 99 Plant  Potted_Plant 
variant 100 Pot  Potted_Plant 
variant 15 Car  Vehicle
variant 131 Window  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 11 Bodywork  Car  Vehicle
variant 5 Bicycle  Vehicle
variant 103 Saddle  Bicycle  Vehicle
variant 46 Handlebar  Bicycle  Vehicle
variant 128 Wheel  Bicycle  Vehicle
variant 128 Wheel  Bicycle  Vehicle
variant 5 Bicycle  Vehicle
variant 103 Saddle  Bicycle  Vehicle
variant 46 Handlebar  Bicycle  Vehicle
variant 128 Wheel  Bicycle  Vehicle
