Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Dog  Animal
Tail  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Torso  Dog  Animal
Nose  Dog  Animal
Muzzle  Dog  Animal
Eye  Dog  Animal
Eye  Dog  Animal
Ear  Dog  Animal
Head  Dog  Animal
Dog  Animal
Torso  Dog  Animal
Nose  Dog  Animal
Muzzle  Dog  Animal
Head  Dog  Animal
