variant 5 Bicycle  Vehicle
variant 46 Handlebar  Bicycle  Vehicle
variant 128 Wheel  Bicycle  Vehicle
variant 98 Person  Animal
variant 67 Leg  Person  Animal
variant 67 Leg  Person  Animal
variant 44 Hand  Person  Animal
variant 2 Arm  Person  Animal
variant 44 Hand  Person  Animal
variant 2 Arm  Person  Animal
variant 122 Torso  Person  Animal
variant 43 Hair  Person  Animal
variant 32 Eye  Person  Animal
variant 26 Ear  Person  Animal
variant 55 Head  Person  Animal
variant 108 TV_Monitor 
variant 104 Screen  TV_Monitor 
variant 12 Bottle 
variant 14 Cap  Bottle 
variant 8 Body  Bottle 
