Person  Animals
Leg  Person  Animals
Leg  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Head  Person  Animals
Dog  Animals
Tail  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Torso  Dog  Animals
Nose  Dog  Animals
Muzzle  Dog  Animals
Ear  Dog  Animals
Ear  Dog  Animals
Head  Dog  Animals
Dog  Animals
Tail  Dog  Animals
Leg  Dog  Animals
Torso  Dog  Animals
Ear  Dog  Animals
Ear  Dog  Animals
Head  Dog  Animals
