Boat  Vehicle
Dining_Table 
Dining_Table 
Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Mouth  Person  Animal
Eyebrow  Person  Animal
Eyebrow  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Chair 
Chair 
Bottle 
Cap  Bottle 
Body  Bottle 
