Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Mirror  Car  Vehicle
Door  Car  Vehicle
Bodywork  Car  Vehicle
Motorbike  Vehicle
Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Mouth  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Ear  Person  Animal
Ear  Person  Animal
Head  Person  Animal
