Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Head  Person  Animals
Person  Animals
Torso  Person  Animals
Head  Person  Animals
Person  Animals
Leg  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Head  Person  Animals
