Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Mirror  Bus  Vehicle
Door  Bus  Vehicle
Bodywork  Bus  Vehicle
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Torso  Person  Animal
Person  Animal
Arm  Person  Animal
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Ear  Person  Animal
Head  Person  Animal
