Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Mirror  Car  Vehicle
Door  Car  Vehicle
Bodywork  Car  Vehicle
Motorbike  Vehicle
Person  Animals
Leg  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Mouth  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Ear  Person  Animals
Ear  Person  Animals
Head  Person  Animals
