variant 22 Dog  Animal
variant 66 Leg  Dog  Animal
variant 66 Leg  Dog  Animal
variant 92 Neck  Dog  Animal
variant 116 Torso  Dog  Animal
variant 94 Nose  Dog  Animal
variant 83 Muzzle  Dog  Animal
variant 34 Eye  Dog  Animal
variant 27 Ear  Dog  Animal
variant 27 Ear  Dog  Animal
variant 48 Head  Dog  Animal
variant 6 Bird  Animal
variant 112 Tail  Bird  Animal
variant 68 Leg  Bird  Animal
variant 68 Leg  Bird  Animal
variant 88 Neck  Bird  Animal
variant 121 Torso  Bird  Animal
variant 4 Beak  Bird  Animal
variant 35 Eye  Bird  Animal
variant 47 Head  Bird  Animal
