Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Arm  Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Hair  Person  Animals
Head  Person  Animals
Train  Vehicle
Headlight  Train  Vehicle
Locomotive  Train  Vehicle
Headlight  Train  Vehicle
Headlight  Train  Vehicle
Headlight  Train  Vehicle
Coach  Train  Vehicle
Coach  Train  Vehicle
