Horse  Animal
Hoof  Horse  Animal
Leg  Horse  Animal
Neck  Horse  Animal
Torso  Horse  Animal
Muzzle  Horse  Animal
Ear  Horse  Animal
Ear  Horse  Animal
Head  Horse  Animal
Horse  Animal
Hoof  Horse  Animal
Leg  Horse  Animal
Hoof  Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Hoof  Horse  Animal
Leg  Horse  Animal
Torso  Horse  Animal
Muzzle  Horse  Animal
Eye  Horse  Animal
Ear  Horse  Animal
Ear  Horse  Animal
Head  Horse  Animal
Bird  Animal
Tail  Bird  Animal
Torso  Bird  Animal
Head  Bird  Animal
