variant 101 Potted_Plant 
variant 99 Plant  Potted_Plant 
variant 100 Pot  Potted_Plant 
variant 101 Potted_Plant 
variant 99 Plant  Potted_Plant 
variant 100 Pot  Potted_Plant 
variant 16 Cat  Animal
variant 111 Tail  Cat  Animal
variant 85 Neck  Cat  Animal
variant 117 Torso  Cat  Animal
variant 49 Head  Cat  Animal
variant 33 Eye  Cat  Animal
variant 33 Eye  Cat  Animal
variant 25 Ear  Cat  Animal
variant 25 Ear  Cat  Animal
