Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Head  Person  Animals
Sheep  Animals
Tail  Sheep  Animals
Torso  Sheep  Animals
Ear  Sheep  Animals
Head  Sheep  Animals
Sheep  Animals
Neck  Sheep  Animals
Torso  Sheep  Animals
Ear  Sheep  Animals
Head  Sheep  Animals
