Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Sheep  Animal
Tail  Sheep  Animal
Torso  Sheep  Animal
Ear  Sheep  Animal
Head  Sheep  Animal
Sheep  Animal
Neck  Sheep  Animal
Torso  Sheep  Animal
Ear  Sheep  Animal
Head  Sheep  Animal
