Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Torso  Dog  Animals
Nose  Dog  Animals
Muzzle  Dog  Animals
Eye  Dog  Animals
Eye  Dog  Animals
Ear  Dog  Animals
Ear  Dog  Animals
Head  Dog  Animals
Cat  Animals
Leg  Cat  Animals
Torso  Cat  Animals
Head  Cat  Animals
Eye  Cat  Animals
Eye  Cat  Animals
Ear  Cat  Animals
Ear  Cat  Animals
