TV_Monitor 
Screen  TV_Monitor 
Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Neck  Dog  Animal
Torso  Dog  Animal
Nose  Dog  Animal
Muzzle  Dog  Animal
Eye  Dog  Animal
Ear  Dog  Animal
Ear  Dog  Animal
Head  Dog  Animal
Dog  Animal
Tail  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Neck  Dog  Animal
Torso  Dog  Animal
Muzzle  Dog  Animal
Ear  Dog  Animal
Head  Dog  Animal
Bottle 
Cap  Bottle 
Body  Bottle 
