variant 98 Person  Animal
variant 44 Hand  Person  Animal
variant 2 Arm  Person  Animal
variant 44 Hand  Person  Animal
variant 2 Arm  Person  Animal
variant 122 Torso  Person  Animal
variant 101 Potted_Plant 
variant 99 Plant  Potted_Plant 
variant 100 Pot  Potted_Plant 
variant 6 Bird  Animal
variant 121 Torso  Bird  Animal
variant 4 Beak  Bird  Animal
variant 35 Eye  Bird  Animal
variant 47 Head  Bird  Animal
