Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Torso  Dog  Animals
Ear  Dog  Animals
Ear  Dog  Animals
Head  Dog  Animals
Dog  Animals
Tail  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Torso  Dog  Animals
Ear  Dog  Animals
Ear  Dog  Animals
Head  Dog  Animals
