Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Torso  Dog  Animal
Ear  Dog  Animal
Ear  Dog  Animal
Head  Dog  Animal
Dog  Animal
Tail  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Torso  Dog  Animal
Ear  Dog  Animal
Ear  Dog  Animal
Head  Dog  Animal
