Person  Animals
Leg  Person  Animals
Leg  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Mouth  Person  Animals
Eyebrow  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Bicycle  Vehicle
Saddle  Bicycle  Vehicle
Handlebar  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
Bottle 
Cap  Bottle 
Body  Bottle 
