variant 16 Cat  Animal
variant 65 Leg  Cat  Animal
variant 85 Neck  Cat  Animal
variant 117 Torso  Cat  Animal
variant 49 Head  Cat  Animal
variant 33 Eye  Cat  Animal
variant 33 Eye  Cat  Animal
variant 25 Ear  Cat  Animal
variant 25 Ear  Cat  Animal
variant 6 Bird  Animal
variant 112 Tail  Bird  Animal
variant 1 Animal_Wing  Bird  Animal
variant 1 Animal_Wing  Bird  Animal
variant 121 Torso  Bird  Animal
