variant 98 Person  Animal
variant 2 Arm  Person  Animal
variant 2 Arm  Person  Animal
variant 87 Neck  Person  Animal
variant 122 Torso  Person  Animal
variant 55 Head  Person  Animal
variant 98 Person  Animal
variant 2 Arm  Person  Animal
variant 122 Torso  Person  Animal
variant 43 Hair  Person  Animal
variant 55 Head  Person  Animal
variant 0 Aeroplane  Vehicle
variant 107 Stern  Aeroplane  Vehicle
variant 127 Wheel  Aeroplane  Vehicle
variant 127 Wheel  Aeroplane  Vehicle
variant 127 Wheel  Aeroplane  Vehicle
variant 31 Engine  Aeroplane  Vehicle
variant 3 Artifact_Wing  Aeroplane  Vehicle
variant 9 Body  Aeroplane  Vehicle
