variant 13 Bus  Vehicle
variant 130 Window  Bus  Vehicle
variant 130 Window  Bus  Vehicle
variant 130 Window  Bus  Vehicle
variant 126 Wheel  Bus  Vehicle
variant 126 Wheel  Bus  Vehicle
variant 56 Headlight  Bus  Vehicle
variant 56 Headlight  Bus  Vehicle
variant 77 Mirror  Bus  Vehicle
variant 77 Mirror  Bus  Vehicle
variant 10 Bodywork  Bus  Vehicle
variant 75 License_Plate  Bus  Vehicle
variant 98 Person  Animal
variant 122 Torso  Person  Animal
variant 55 Head  Person  Animal
variant 98 Person  Animal
variant 44 Hand  Person  Animal
variant 2 Arm  Person  Animal
variant 44 Hand  Person  Animal
variant 2 Arm  Person  Animal
variant 122 Torso  Person  Animal
variant 55 Head  Person  Animal
variant 5 Bicycle  Vehicle
variant 103 Saddle  Bicycle  Vehicle
variant 46 Handlebar  Bicycle  Vehicle
variant 17 Chain_Wheel  Bicycle  Vehicle
variant 128 Wheel  Bicycle  Vehicle
variant 128 Wheel  Bicycle  Vehicle
