Person  Animals
Leg  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Hair  Person  Animals
Head  Person  Animals
Sheep  Animals
Muzzle  Sheep  Animals
Eye  Sheep  Animals
Ear  Sheep  Animals
Ear  Sheep  Animals
Head  Sheep  Animals
Sheep  Animals
Torso  Sheep  Animals
Muzzle  Sheep  Animals
Eye  Sheep  Animals
Ear  Sheep  Animals
Head  Sheep  Animals
