Horse  Animal
Tail  Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Torso  Horse  Animal
Muzzle  Horse  Animal
Ear  Horse  Animal
Ear  Horse  Animal
Head  Horse  Animal
Person  Animal
Leg  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Headlight  Car  Vehicle
Headlight  Car  Vehicle
Bodywork  Car  Vehicle
