Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Mouth  Person  Animal
Eyebrow  Person  Animal
Eye  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Bird  Animal
Tail  Bird  Animal
Leg  Bird  Animal
Leg  Bird  Animal
Animal_Wing  Bird  Animal
Animal_Wing  Bird  Animal
Neck  Bird  Animal
Torso  Bird  Animal
Beak  Bird  Animal
Eye  Bird  Animal
Head  Bird  Animal
