variant 13 Bus  Vehicle
variant 130 Window  Bus  Vehicle
variant 126 Wheel  Bus  Vehicle
variant 126 Wheel  Bus  Vehicle
variant 56 Headlight  Bus  Vehicle
variant 10 Bodywork  Bus  Vehicle
variant 15 Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 11 Bodywork  Car  Vehicle
variant 79 Motorbike  Vehicle
variant 57 Headlight  Motorbike  Vehicle
variant 129 Wheel  Motorbike  Vehicle
variant 129 Wheel  Motorbike  Vehicle
