variant 64 Horse  Animal
variant 113 Tail  Horse  Animal
variant 71 Leg  Horse  Animal
variant 71 Leg  Horse  Animal
variant 71 Leg  Horse  Animal
variant 71 Leg  Horse  Animal
variant 115 Torso  Horse  Animal
variant 81 Muzzle  Horse  Animal
variant 30 Ear  Horse  Animal
variant 30 Ear  Horse  Animal
variant 51 Head  Horse  Animal
variant 98 Person  Animal
variant 67 Leg  Person  Animal
variant 122 Torso  Person  Animal
variant 55 Head  Person  Animal
variant 15 Car  Vehicle
variant 131 Window  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 59 Headlight  Car  Vehicle
variant 59 Headlight  Car  Vehicle
variant 11 Bodywork  Car  Vehicle
