variant 98 Person  Animal
variant 67 Leg  Person  Animal
variant 67 Leg  Person  Animal
variant 44 Hand  Person  Animal
variant 2 Arm  Person  Animal
variant 122 Torso  Person  Animal
variant 43 Hair  Person  Animal
variant 55 Head  Person  Animal
variant 105 Sheep  Animal
variant 82 Muzzle  Sheep  Animal
variant 37 Eye  Sheep  Animal
variant 29 Ear  Sheep  Animal
variant 29 Ear  Sheep  Animal
variant 54 Head  Sheep  Animal
variant 105 Sheep  Animal
variant 123 Torso  Sheep  Animal
variant 82 Muzzle  Sheep  Animal
variant 37 Eye  Sheep  Animal
variant 29 Ear  Sheep  Animal
variant 54 Head  Sheep  Animal
