variant 98 Person  Animal
variant 87 Neck  Person  Animal
variant 95 Nose  Person  Animal
variant 80 Mouth  Person  Animal
variant 41 Eyebrow  Person  Animal
variant 41 Eyebrow  Person  Animal
variant 32 Eye  Person  Animal
variant 32 Eye  Person  Animal
variant 55 Head  Person  Animal
variant 22 Dog  Animal
variant 92 Neck  Dog  Animal
variant 116 Torso  Dog  Animal
variant 94 Nose  Dog  Animal
variant 83 Muzzle  Dog  Animal
variant 34 Eye  Dog  Animal
variant 27 Ear  Dog  Animal
variant 48 Head  Dog  Animal
