variant 22 Dog  Animal
variant 116 Torso  Dog  Animal
variant 94 Nose  Dog  Animal
variant 83 Muzzle  Dog  Animal
variant 34 Eye  Dog  Animal
variant 27 Ear  Dog  Animal
variant 48 Head  Dog  Animal
variant 105 Sheep  Animal
variant 123 Torso  Sheep  Animal
variant 82 Muzzle  Sheep  Animal
variant 37 Eye  Sheep  Animal
variant 29 Ear  Sheep  Animal
variant 54 Head  Sheep  Animal
variant 105 Sheep  Animal
variant 123 Torso  Sheep  Animal
variant 82 Muzzle  Sheep  Animal
variant 29 Ear  Sheep  Animal
variant 29 Ear  Sheep  Animal
variant 54 Head  Sheep  Animal
variant 105 Sheep  Animal
variant 123 Torso  Sheep  Animal
variant 82 Muzzle  Sheep  Animal
variant 37 Eye  Sheep  Animal
variant 29 Ear  Sheep  Animal
variant 54 Head  Sheep  Animal
variant 105 Sheep  Animal
variant 123 Torso  Sheep  Animal
variant 82 Muzzle  Sheep  Animal
variant 62 Horn  Sheep  Animal
variant 37 Eye  Sheep  Animal
variant 54 Head  Sheep  Animal
variant 105 Sheep  Animal
variant 86 Neck  Sheep  Animal
variant 123 Torso  Sheep  Animal
variant 82 Muzzle  Sheep  Animal
variant 62 Horn  Sheep  Animal
variant 62 Horn  Sheep  Animal
variant 37 Eye  Sheep  Animal
variant 37 Eye  Sheep  Animal
variant 54 Head  Sheep  Animal
variant 22 Dog  Animal
variant 110 Tail  Dog  Animal
variant 66 Leg  Dog  Animal
variant 116 Torso  Dog  Animal
variant 105 Sheep  Animal
variant 123 Torso  Sheep  Animal
variant 82 Muzzle  Sheep  Animal
variant 62 Horn  Sheep  Animal
variant 54 Head  Sheep  Animal
variant 105 Sheep  Animal
variant 123 Torso  Sheep  Animal
variant 82 Muzzle  Sheep  Animal
variant 37 Eye  Sheep  Animal
variant 29 Ear  Sheep  Animal
variant 29 Ear  Sheep  Animal
variant 54 Head  Sheep  Animal
