variant 64 Horse  Animal
variant 93 Neck  Horse  Animal
variant 115 Torso  Horse  Animal
variant 81 Muzzle  Horse  Animal
variant 36 Eye  Horse  Animal
variant 30 Ear  Horse  Animal
variant 30 Ear  Horse  Animal
variant 51 Head  Horse  Animal
variant 15 Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 125 Wheel  Car  Vehicle
variant 59 Headlight  Car  Vehicle
variant 11 Bodywork  Car  Vehicle
