Sheep  Animal
Tail  Sheep  Animal
Torso  Sheep  Animal
Ear  Sheep  Animal
Head  Sheep  Animal
Bird  Animal
Tail  Bird  Animal
Leg  Bird  Animal
Leg  Bird  Animal
Torso  Bird  Animal
Bird  Animal
Tail  Bird  Animal
Torso  Bird  Animal
Beak  Bird  Animal
Head  Bird  Animal
Bird  Animal
Tail  Bird  Animal
Leg  Bird  Animal
Leg  Bird  Animal
Animal_Wing  Bird  Animal
Torso  Bird  Animal
Beak  Bird  Animal
Head  Bird  Animal
