Sheep  Animals
Tail  Sheep  Animals
Torso  Sheep  Animals
Ear  Sheep  Animals
Head  Sheep  Animals
Bird  Animals
Tail  Bird  Animals
Leg  Bird  Animals
Leg  Bird  Animals
Torso  Bird  Animals
Bird  Animals
Tail  Bird  Animals
Torso  Bird  Animals
Beak  Bird  Animals
Head  Bird  Animals
Bird  Animals
Tail  Bird  Animals
Leg  Bird  Animals
Leg  Bird  Animals
Animal_Wing  Bird  Animals
Torso  Bird  Animals
Beak  Bird  Animals
Head  Bird  Animals
