Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Mouth  Person  Animals
Head  Person  Animals
Sheep  Animals
Tail  Sheep  Animals
Torso  Sheep  Animals
Ear  Sheep  Animals
Head  Sheep  Animals
Sheep  Animals
Tail  Sheep  Animals
Torso  Sheep  Animals
Muzzle  Sheep  Animals
Ear  Sheep  Animals
Head  Sheep  Animals
Sheep  Animals
Neck  Sheep  Animals
Torso  Sheep  Animals
Ear  Sheep  Animals
Head  Sheep  Animals
