Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Mouth  Person  Animal
Head  Person  Animal
Sheep  Animal
Tail  Sheep  Animal
Torso  Sheep  Animal
Ear  Sheep  Animal
Head  Sheep  Animal
Sheep  Animal
Tail  Sheep  Animal
Torso  Sheep  Animal
Muzzle  Sheep  Animal
Ear  Sheep  Animal
Head  Sheep  Animal
Sheep  Animal
Neck  Sheep  Animal
Torso  Sheep  Animal
Ear  Sheep  Animal
Head  Sheep  Animal
