variant 105 Sheep  Animal
variant 86 Neck  Sheep  Animal
variant 123 Torso  Sheep  Animal
variant 82 Muzzle  Sheep  Animal
variant 62 Horn  Sheep  Animal
variant 62 Horn  Sheep  Animal
variant 37 Eye  Sheep  Animal
variant 37 Eye  Sheep  Animal
variant 29 Ear  Sheep  Animal
variant 54 Head  Sheep  Animal
variant 20 Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 91 Neck  Cow  Animal
variant 118 Torso  Cow  Animal
variant 84 Muzzle  Cow  Animal
variant 28 Ear  Cow  Animal
variant 50 Head  Cow  Animal
