Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Mouth  Person  Animals
Eyebrow  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Sheep  Animals
Torso  Sheep  Animals
Muzzle  Sheep  Animals
Horn  Sheep  Animals
Horn  Sheep  Animals
Eye  Sheep  Animals
Ear  Sheep  Animals
Head  Sheep  Animals
