variant 6 Bird  Animal
variant 68 Leg  Bird  Animal
variant 68 Leg  Bird  Animal
variant 88 Neck  Bird  Animal
variant 121 Torso  Bird  Animal
variant 4 Beak  Bird  Animal
variant 35 Eye  Bird  Animal
variant 35 Eye  Bird  Animal
variant 47 Head  Bird  Animal
variant 105 Sheep  Animal
variant 109 Tail  Sheep  Animal
variant 86 Neck  Sheep  Animal
variant 123 Torso  Sheep  Animal
variant 29 Ear  Sheep  Animal
variant 29 Ear  Sheep  Animal
variant 54 Head  Sheep  Animal
variant 105 Sheep  Animal
variant 86 Neck  Sheep  Animal
variant 123 Torso  Sheep  Animal
variant 37 Eye  Sheep  Animal
variant 29 Ear  Sheep  Animal
variant 29 Ear  Sheep  Animal
variant 54 Head  Sheep  Animal
