Bird  Animal
Leg  Bird  Animal
Leg  Bird  Animal
Neck  Bird  Animal
Torso  Bird  Animal
Beak  Bird  Animal
Eye  Bird  Animal
Eye  Bird  Animal
Head  Bird  Animal
Sheep  Animal
Tail  Sheep  Animal
Neck  Sheep  Animal
Torso  Sheep  Animal
Ear  Sheep  Animal
Ear  Sheep  Animal
Head  Sheep  Animal
Sheep  Animal
Neck  Sheep  Animal
Torso  Sheep  Animal
Eye  Sheep  Animal
Ear  Sheep  Animal
Ear  Sheep  Animal
Head  Sheep  Animal
