variant 98 Person  Animal
variant 44 Hand  Person  Animal
variant 2 Arm  Person  Animal
variant 44 Hand  Person  Animal
variant 2 Arm  Person  Animal
variant 122 Torso  Person  Animal
variant 16 Cat  Animal
variant 111 Tail  Cat  Animal
variant 65 Leg  Cat  Animal
variant 65 Leg  Cat  Animal
variant 65 Leg  Cat  Animal
variant 85 Neck  Cat  Animal
variant 117 Torso  Cat  Animal
variant 49 Head  Cat  Animal
variant 25 Ear  Cat  Animal
