Sofa 
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Eye  Person  Animal
Ear  Person  Animal
Head  Person  Animal
TV_Monitor 
Screen  TV_Monitor 
Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Neck  Dog  Animal
Torso  Dog  Animal
Nose  Dog  Animal
Muzzle  Dog  Animal
Eye  Dog  Animal
Ear  Dog  Animal
Head  Dog  Animal
