Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Ear  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Head  Person  Animal
Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Sheep  Animal
Torso  Sheep  Animal
Head  Sheep  Animal
