Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Torso  Cow  Animal
Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Neck  Cow  Animal
Torso  Cow  Animal
Horn  Cow  Animal
Head  Cow  Animal
Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Horn  Cow  Animal
Horn  Cow  Animal
Eye  Cow  Animal
Head  Cow  Animal
Cow  Animal
Tail  Cow  Animal
Neck  Cow  Animal
Torso  Cow  Animal
Head  Cow  Animal
