variant 105 Sheep  Animal
variant 123 Torso  Sheep  Animal
variant 62 Horn  Sheep  Animal
variant 62 Horn  Sheep  Animal
variant 29 Ear  Sheep  Animal
variant 54 Head  Sheep  Animal
variant 79 Motorbike  Vehicle
variant 129 Wheel  Motorbike  Vehicle
variant 79 Motorbike  Vehicle
variant 129 Wheel  Motorbike  Vehicle
variant 129 Wheel  Motorbike  Vehicle
variant 79 Motorbike  Vehicle
variant 129 Wheel  Motorbike  Vehicle
variant 129 Wheel  Motorbike  Vehicle
variant 13 Bus  Vehicle
variant 130 Window  Bus  Vehicle
variant 130 Window  Bus  Vehicle
variant 10 Bodywork  Bus  Vehicle
