Horse  Animal
Tail  Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Neck  Horse  Animal
Torso  Horse  Animal
Muzzle  Horse  Animal
Eye  Horse  Animal
Ear  Horse  Animal
Ear  Horse  Animal
Head  Horse  Animal
Bird  Animal
Tail  Bird  Animal
Leg  Bird  Animal
Leg  Bird  Animal
Neck  Bird  Animal
Torso  Bird  Animal
Beak  Bird  Animal
Eye  Bird  Animal
Head  Bird  Animal
