Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Head  Person  Animal
Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Eye  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Person  Animal
Arm  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Mouth  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Person  Animal
Arm  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Head  Person  Animal
Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Head  Person  Animal
Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Door  Car  Vehicle
Bodywork  Car  Vehicle
