Dog  Animal
Tail  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Neck  Dog  Animal
Torso  Dog  Animal
Nose  Dog  Animal
Muzzle  Dog  Animal
Eye  Dog  Animal
Eye  Dog  Animal
Ear  Dog  Animal
Ear  Dog  Animal
Head  Dog  Animal
Bicycle  Vehicle
Wheel  Bicycle  Vehicle
Bicycle  Vehicle
Saddle  Bicycle  Vehicle
Handlebar  Bicycle  Vehicle
Chain_Wheel  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
