variant 22 Dog  Animal
variant 110 Tail  Dog  Animal
variant 66 Leg  Dog  Animal
variant 66 Leg  Dog  Animal
variant 66 Leg  Dog  Animal
variant 66 Leg  Dog  Animal
variant 92 Neck  Dog  Animal
variant 116 Torso  Dog  Animal
variant 94 Nose  Dog  Animal
variant 83 Muzzle  Dog  Animal
variant 34 Eye  Dog  Animal
variant 34 Eye  Dog  Animal
variant 27 Ear  Dog  Animal
variant 27 Ear  Dog  Animal
variant 48 Head  Dog  Animal
variant 5 Bicycle  Vehicle
variant 128 Wheel  Bicycle  Vehicle
variant 5 Bicycle  Vehicle
variant 103 Saddle  Bicycle  Vehicle
variant 46 Handlebar  Bicycle  Vehicle
variant 17 Chain_Wheel  Bicycle  Vehicle
variant 128 Wheel  Bicycle  Vehicle
variant 128 Wheel  Bicycle  Vehicle
