Car  Vehicle
Window  Car  Vehicle
Bodywork  Car  Vehicle
Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Motorbike  Vehicle
Headlight  Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Motorbike  Vehicle
Wheel  Motorbike  Vehicle
