Person  Animals
Leg  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Neck  Dog  Animals
Torso  Dog  Animals
Nose  Dog  Animals
Muzzle  Dog  Animals
Eye  Dog  Animals
Ear  Dog  Animals
Head  Dog  Animals
Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Neck  Dog  Animals
Torso  Dog  Animals
Nose  Dog  Animals
Muzzle  Dog  Animals
Eye  Dog  Animals
Ear  Dog  Animals
Head  Dog  Animals
