Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Torso  Horse  Animal
Muzzle  Horse  Animal
Head  Horse  Animal
Horse  Animal
Tail  Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Neck  Horse  Animal
Torso  Horse  Animal
Muzzle  Horse  Animal
Ear  Horse  Animal
Head  Horse  Animal
Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Head  Person  Animal
