Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Door  Car  Vehicle
Bodywork  Car  Vehicle
Person  Animal
Leg  Person  Animal
Torso  Person  Animal
Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Bicycle  Vehicle
Saddle  Bicycle  Vehicle
Handlebar  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Mouth  Person  Animal
Eyebrow  Person  Animal
Eyebrow  Person  Animal
Ear  Person  Animal
Head  Person  Animal
