Dining_Table 
Sofa 
Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Mouth  Person  Animals
Eyebrow  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Chair 
TV_Monitor 
Screen  TV_Monitor 
Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Torso  Dog  Animals
Nose  Dog  Animals
Muzzle  Dog  Animals
Eye  Dog  Animals
Ear  Dog  Animals
Ear  Dog  Animals
Head  Dog  Animals
