Boat  Vehicle
Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Hair  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Person  Animals
Leg  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Boat  Vehicle
Dog  Animals
Tail  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Torso  Dog  Animals
Muzzle  Dog  Animals
Ear  Dog  Animals
Head  Dog  Animals
