Boat  Vehicle
Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Boat  Vehicle
Dog  Animal
Tail  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Torso  Dog  Animal
Muzzle  Dog  Animal
Ear  Dog  Animal
Head  Dog  Animal
