Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Eyebrow  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Head  Person  Animals
Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Mouth  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Horse  Animals
Hoof  Horse  Animals
Leg  Horse  Animals
Hoof  Horse  Animals
Leg  Horse  Animals
Torso  Horse  Animals
Ear  Horse  Animals
Head  Horse  Animals
Horse  Animals
Tail  Horse  Animals
Leg  Horse  Animals
Hoof  Horse  Animals
Leg  Horse  Animals
Leg  Horse  Animals
Hoof  Horse  Animals
Leg  Horse  Animals
Torso  Horse  Animals
Muzzle  Horse  Animals
Ear  Horse  Animals
Ear  Horse  Animals
Head  Horse  Animals
