Person  Animals
Leg  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Hair  Person  Animals
Head  Person  Animals
Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Mouth  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Head  Person  Animals
Person  Animals
Foot  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Mouth  Person  Animals
Head  Person  Animals
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Motorbike  Vehicle
Headlight  Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Wheel  Motorbike  Vehicle
