Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Mouth  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Chair 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
