Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Mouth  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Chair 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
