Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Head  Person  Animal
Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Head  Person  Animal
Motorbike  Vehicle
Headlight  Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Hand  Person  Animal
Torso  Person  Animal
