Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Mouth  Person  Animals
Eyebrow  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Cat  Animals
Leg  Cat  Animals
Leg  Cat  Animals
Neck  Cat  Animals
Torso  Cat  Animals
Head  Cat  Animals
Ear  Cat  Animals
Ear  Cat  Animals
Cat  Animals
Tail  Cat  Animals
Leg  Cat  Animals
Leg  Cat  Animals
Leg  Cat  Animals
Neck  Cat  Animals
Torso  Cat  Animals
Head  Cat  Animals
Eye  Cat  Animals
Ear  Cat  Animals
Ear  Cat  Animals
