Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Mirror  Car  Vehicle
Bodywork  Car  Vehicle
Horse  Animal
Tail  Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Leg  Horse  Animal
Neck  Horse  Animal
Torso  Horse  Animal
Muzzle  Horse  Animal
Eye  Horse  Animal
Head  Horse  Animal
Horse  Animal
Tail  Horse  Animal
Hoof  Horse  Animal
Leg  Horse  Animal
Hoof  Horse  Animal
Leg  Horse  Animal
Hoof  Horse  Animal
Leg  Horse  Animal
Hoof  Horse  Animal
Leg  Horse  Animal
Neck  Horse  Animal
Torso  Horse  Animal
Muzzle  Horse  Animal
Eye  Horse  Animal
Head  Horse  Animal
