Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Nose  Person  Animal
Eyebrow  Person  Animal
Head  Person  Animal
Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Headlight  Car  Vehicle
Headlight  Car  Vehicle
Mirror  Car  Vehicle
Mirror  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Mouth  Person  Animal
Head  Person  Animal
Bicycle  Vehicle
Saddle  Bicycle  Vehicle
Handlebar  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
Bicycle  Vehicle
Saddle  Bicycle  Vehicle
Handlebar  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
Bicycle  Vehicle
Handlebar  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
