Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Mouth  Person  Animals
Eyebrow  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Head  Person  Animals
TV_Monitor 
Screen  TV_Monitor 
Cat  Animals
Leg  Cat  Animals
Leg  Cat  Animals
Neck  Cat  Animals
Torso  Cat  Animals
Head  Cat  Animals
Eye  Cat  Animals
Eye  Cat  Animals
Ear  Cat  Animals
Ear  Cat  Animals
Cat  Animals
Neck  Cat  Animals
Head  Cat  Animals
Eye  Cat  Animals
Eye  Cat  Animals
Ear  Cat  Animals
Ear  Cat  Animals
