Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Headlight  Car  Vehicle
Mirror  Car  Vehicle
Bodywork  Car  Vehicle
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Headlight  Car  Vehicle
Mirror  Car  Vehicle
Door  Car  Vehicle
Door  Car  Vehicle
Bodywork  Car  Vehicle
Bicycle  Vehicle
Saddle  Bicycle  Vehicle
Handlebar  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
