Chair 
TV_Monitor 
TV_Monitor 
Screen  TV_Monitor 
TV_Monitor 
TV_Monitor 
Screen  TV_Monitor 
TV_Monitor 
Screen  TV_Monitor 
Chair 
Chair 
Chair 
Chair 
Chair 
Chair 
Chair 
Chair 
Chair 
Chair 
TV_Monitor 
Screen  TV_Monitor 
TV_Monitor 
Screen  TV_Monitor 
TV_Monitor 
Screen  TV_Monitor 
TV_Monitor 
Screen  TV_Monitor 
TV_Monitor 
Screen  TV_Monitor 
TV_Monitor 
Screen  TV_Monitor 
TV_Monitor 
Screen  TV_Monitor 
TV_Monitor 
Screen  TV_Monitor 
TV_Monitor 
Screen  TV_Monitor 
TV_Monitor 
Screen  TV_Monitor 
TV_Monitor 
Screen  TV_Monitor 
