variant 98 Person  Animal
variant 42 Foot  Person  Animal
variant 67 Leg  Person  Animal
variant 42 Foot  Person  Animal
variant 67 Leg  Person  Animal
variant 122 Torso  Person  Animal
variant 95 Nose  Person  Animal
variant 43 Hair  Person  Animal
variant 80 Mouth  Person  Animal
variant 41 Eyebrow  Person  Animal
variant 41 Eyebrow  Person  Animal
variant 32 Eye  Person  Animal
variant 32 Eye  Person  Animal
variant 26 Ear  Person  Animal
variant 55 Head  Person  Animal
variant 98 Person  Animal
variant 42 Foot  Person  Animal
variant 67 Leg  Person  Animal
variant 42 Foot  Person  Animal
variant 67 Leg  Person  Animal
variant 2 Arm  Person  Animal
variant 122 Torso  Person  Animal
variant 95 Nose  Person  Animal
variant 80 Mouth  Person  Animal
variant 41 Eyebrow  Person  Animal
variant 41 Eyebrow  Person  Animal
variant 32 Eye  Person  Animal
variant 32 Eye  Person  Animal
variant 26 Ear  Person  Animal
variant 55 Head  Person  Animal
variant 6 Bird  Animal
variant 112 Tail  Bird  Animal
variant 68 Leg  Bird  Animal
variant 68 Leg  Bird  Animal
variant 88 Neck  Bird  Animal
variant 121 Torso  Bird  Animal
variant 47 Head  Bird  Animal
