Person  Animals
Leg  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Mouth  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Head  Person  Animals
Person  Animals
Leg  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Mouth  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Bird  Animals
Leg  Bird  Animals
Leg  Bird  Animals
Neck  Bird  Animals
Torso  Bird  Animals
Head  Bird  Animals
Bird  Animals
Tail  Bird  Animals
Leg  Bird  Animals
Leg  Bird  Animals
Torso  Bird  Animals
Head  Bird  Animals
