Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Mouth  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Sheep  Animal
Tail  Sheep  Animal
Leg  Sheep  Animal
Leg  Sheep  Animal
Torso  Sheep  Animal
Ear  Sheep  Animal
Head  Sheep  Animal
Sheep  Animal
Tail  Sheep  Animal
Leg  Sheep  Animal
Leg  Sheep  Animal
Leg  Sheep  Animal
Leg  Sheep  Animal
Neck  Sheep  Animal
Torso  Sheep  Animal
Ear  Sheep  Animal
Ear  Sheep  Animal
Head  Sheep  Animal
Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Wheel  Motorbike  Vehicle
