Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Mouth  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Head  Person  Animal
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Head  Person  Animal
Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Eyebrow  Person  Animal
Eye  Person  Animal
Head  Person  Animal
Car  Vehicle
Wheel  Car  Vehicle
Headlight  Car  Vehicle
Bodywork  Car  Vehicle
Bus  Vehicle
Wheel  Bus  Vehicle
Bodywork  Bus  Vehicle
