Train  Vehicle
Locomotive  Train  Vehicle
Headlight  Train  Vehicle
Headlight  Train  Vehicle
Headlight  Train  Vehicle
Person  Animals
Leg  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Hair  Person  Animals
Head  Person  Animals
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Door  Bus  Vehicle
Bodywork  Bus  Vehicle
Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Bodywork  Car  Vehicle
