Train  Vehicle
Locomotive  Train  Vehicle
Headlight  Train  Vehicle
Headlight  Train  Vehicle
Headlight  Train  Vehicle
Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Head  Person  Animal
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Door  Bus  Vehicle
Bodywork  Bus  Vehicle
Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Bodywork  Car  Vehicle
