Person  Animals
Arm  Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Mouth  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Person  Animals
Arm  Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Mouth  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Cow  Animals
Tail  Cow  Animals
Leg  Cow  Animals
Leg  Cow  Animals
Torso  Cow  Animals
Cow  Animals
Leg  Cow  Animals
Leg  Cow  Animals
Leg  Cow  Animals
Neck  Cow  Animals
Torso  Cow  Animals
Muzzle  Cow  Animals
Eye  Cow  Animals
Head  Cow  Animals
