Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Bodywork  Car  Vehicle
Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Bodywork  Car  Vehicle
Car  Vehicle
Bodywork  Car  Vehicle
Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Door  Car  Vehicle
Door  Car  Vehicle
Bodywork  Car  Vehicle
Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Door  Car  Vehicle
Bodywork  Car  Vehicle
License_Plate  Car  Vehicle
