Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Boat  Vehicle
Person  Animal
Arm  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Eye  Person  Animal
Eye  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Head  Person  Animal
Chair 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Potted_Plant 
Plant  Potted_Plant 
Pot  Potted_Plant 
Motorbike  Vehicle
Wheel  Motorbike  Vehicle
Wheel  Motorbike  Vehicle
