Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Wheel  Car  Vehicle
Mirror  Car  Vehicle
Bodywork  Car  Vehicle
Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Wheel  Bus  Vehicle
Wheel  Bus  Vehicle
Headlight  Bus  Vehicle
Headlight  Bus  Vehicle
Mirror  Bus  Vehicle
Mirror  Bus  Vehicle
Bodywork  Bus  Vehicle
License_Plate  Bus  Vehicle
Bicycle  Vehicle
Handlebar  Bicycle  Vehicle
Bicycle  Vehicle
Saddle  Bicycle  Vehicle
Handlebar  Bicycle  Vehicle
Wheel  Bicycle  Vehicle
Person  Animals
Arm  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Mouth  Person  Animals
Eyebrow  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Ear  Person  Animals
Head  Person  Animals
