Cow  Animal
Tail  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Torso  Cow  Animal
Cow  Animal
Tail  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Torso  Cow  Animal
Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Torso  Cow  Animal
Cow  Animal
Tail  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Torso  Cow  Animal
Cow  Animal
Tail  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Torso  Cow  Animal
Cow  Animal
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Mouth  Person  Animal
Eyebrow  Person  Animal
Eye  Person  Animal
Ear  Person  Animal
Head  Person  Animal
