Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Neck  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Mouth  Person  Animals
Eyebrow  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Arm  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Head  Person  Animals
Sheep  Animals
Neck  Sheep  Animals
Torso  Sheep  Animals
Muzzle  Sheep  Animals
Eye  Sheep  Animals
Head  Sheep  Animals
Horse  Animals
Leg  Horse  Animals
Neck  Horse  Animals
Torso  Horse  Animals
Muzzle  Horse  Animals
Eye  Horse  Animals
Ear  Horse  Animals
Head  Horse  Animals
