Person  Animal
Leg  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Mouth  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Dog  Animal
Tail  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Neck  Dog  Animal
Torso  Dog  Animal
Muzzle  Dog  Animal
Ear  Dog  Animal
Ear  Dog  Animal
Head  Dog  Animal
Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Neck  Dog  Animal
Torso  Dog  Animal
Nose  Dog  Animal
Muzzle  Dog  Animal
Head  Dog  Animal
