Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Neck  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Torso  Person  Animal
Head  Person  Animal
Cow  Animal
Tail  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Torso  Cow  Animal
Muzzle  Cow  Animal
Horn  Cow  Animal
Horn  Cow  Animal
Eye  Cow  Animal
Eye  Cow  Animal
Ear  Cow  Animal
Ear  Cow  Animal
Head  Cow  Animal
