Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Wheel  Bus  Vehicle
Wheel  Bus  Vehicle
Headlight  Bus  Vehicle
Headlight  Bus  Vehicle
Mirror  Bus  Vehicle
Door  Bus  Vehicle
Bodywork  Bus  Vehicle
Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Wheel  Bus  Vehicle
Wheel  Bus  Vehicle
Wheel  Bus  Vehicle
Headlight  Bus  Vehicle
Headlight  Bus  Vehicle
Mirror  Bus  Vehicle
Mirror  Bus  Vehicle
Door  Bus  Vehicle
Bodywork  Bus  Vehicle
License_Plate  Bus  Vehicle
Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Torso  Person  Animal
Head  Person  Animal
