Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Mouth  Person  Animal
Eye  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Sheep  Animal
Torso  Sheep  Animal
Muzzle  Sheep  Animal
Ear  Sheep  Animal
Head  Sheep  Animal
Sheep  Animal
Torso  Sheep  Animal
Muzzle  Sheep  Animal
Ear  Sheep  Animal
Ear  Sheep  Animal
Head  Sheep  Animal
Sheep  Animal
Torso  Sheep  Animal
Muzzle  Sheep  Animal
Ear  Sheep  Animal
Head  Sheep  Animal
Sheep  Animal
Tail  Sheep  Animal
Neck  Sheep  Animal
Torso  Sheep  Animal
Muzzle  Sheep  Animal
Ear  Sheep  Animal
Head  Sheep  Animal
