Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Head  Person  Animal
Boat  Vehicle
Boat  Vehicle
Car  Vehicle
Window  Car  Vehicle
Window  Car  Vehicle
Wheel  Car  Vehicle
Mirror  Car  Vehicle
Bodywork  Car  Vehicle
Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Wheel  Bus  Vehicle
Wheel  Bus  Vehicle
Wheel  Bus  Vehicle
Headlight  Bus  Vehicle
Headlight  Bus  Vehicle
Mirror  Bus  Vehicle
Mirror  Bus  Vehicle
Bodywork  Bus  Vehicle
Bus  Vehicle
Window  Bus  Vehicle
Window  Bus  Vehicle
Wheel  Bus  Vehicle
Wheel  Bus  Vehicle
Bodywork  Bus  Vehicle
