Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Neck  Dog  Animal
Torso  Dog  Animal
Nose  Dog  Animal
Muzzle  Dog  Animal
Ear  Dog  Animal
Ear  Dog  Animal
Head  Dog  Animal
Cat  Animal
Leg  Cat  Animal
Leg  Cat  Animal
Leg  Cat  Animal
Torso  Cat  Animal
Head  Cat  Animal
Ear  Cat  Animal
Ear  Cat  Animal
Dog  Animal
Tail  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Neck  Dog  Animal
Torso  Dog  Animal
Nose  Dog  Animal
Muzzle  Dog  Animal
Eye  Dog  Animal
Eye  Dog  Animal
Ear  Dog  Animal
Ear  Dog  Animal
Head  Dog  Animal
