Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Hair  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Cow  Animals
Cow  Animals
Torso  Cow  Animals
Cow  Animals
Tail  Cow  Animals
Leg  Cow  Animals
Leg  Cow  Animals
Leg  Cow  Animals
Leg  Cow  Animals
Torso  Cow  Animals
Eye  Cow  Animals
Eye  Cow  Animals
Ear  Cow  Animals
Head  Cow  Animals
Cow  Animals
Leg  Cow  Animals
Leg  Cow  Animals
Leg  Cow  Animals
Leg  Cow  Animals
Torso  Cow  Animals
Muzzle  Cow  Animals
Eye  Cow  Animals
Eye  Cow  Animals
Ear  Cow  Animals
Ear  Cow  Animals
Head  Cow  Animals
