Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Hair  Person  Animal
Eyebrow  Person  Animal
Eye  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Cow  Animal
Cow  Animal
Torso  Cow  Animal
Cow  Animal
Tail  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Torso  Cow  Animal
Eye  Cow  Animal
Eye  Cow  Animal
Ear  Cow  Animal
Head  Cow  Animal
Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Torso  Cow  Animal
Muzzle  Cow  Animal
Eye  Cow  Animal
Eye  Cow  Animal
Ear  Cow  Animal
Ear  Cow  Animal
Head  Cow  Animal
