Person  Animals
Torso  Person  Animals
Head  Person  Animals
Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Hair  Person  Animals
Head  Person  Animals
Person  Animals
Arm  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Hair  Person  Animals
Ear  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Hair  Person  Animals
Head  Person  Animals
Person  Animals
Arm  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Hair  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Hair  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Car  Vehicle
Wheel  Car  Vehicle
Bodywork  Car  Vehicle
