Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Nose  Person  Animal
Hair  Person  Animal
Mouth  Person  Animal
Head  Person  Animal
Person  Animal
Leg  Person  Animal
Foot  Person  Animal
Leg  Person  Animal
Arm  Person  Animal
Hand  Person  Animal
Arm  Person  Animal
Torso  Person  Animal
Ear  Person  Animal
Ear  Person  Animal
Head  Person  Animal
Sheep  Animal
Neck  Sheep  Animal
Torso  Sheep  Animal
Head  Sheep  Animal
Dog  Animal
Tail  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Leg  Dog  Animal
Torso  Dog  Animal
Muzzle  Dog  Animal
Ear  Dog  Animal
Ear  Dog  Animal
Head  Dog  Animal
