variant 98 Person  Animal
variant 42 Foot  Person  Animal
variant 67 Leg  Person  Animal
variant 2 Arm  Person  Animal
variant 122 Torso  Person  Animal
variant 95 Nose  Person  Animal
variant 43 Hair  Person  Animal
variant 80 Mouth  Person  Animal
variant 55 Head  Person  Animal
variant 98 Person  Animal
variant 67 Leg  Person  Animal
variant 42 Foot  Person  Animal
variant 67 Leg  Person  Animal
variant 2 Arm  Person  Animal
variant 44 Hand  Person  Animal
variant 2 Arm  Person  Animal
variant 122 Torso  Person  Animal
variant 26 Ear  Person  Animal
variant 26 Ear  Person  Animal
variant 55 Head  Person  Animal
variant 105 Sheep  Animal
variant 86 Neck  Sheep  Animal
variant 123 Torso  Sheep  Animal
variant 54 Head  Sheep  Animal
variant 22 Dog  Animal
variant 110 Tail  Dog  Animal
variant 66 Leg  Dog  Animal
variant 66 Leg  Dog  Animal
variant 66 Leg  Dog  Animal
variant 66 Leg  Dog  Animal
variant 116 Torso  Dog  Animal
variant 83 Muzzle  Dog  Animal
variant 27 Ear  Dog  Animal
variant 27 Ear  Dog  Animal
variant 48 Head  Dog  Animal
