Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Hair  Person  Animals
Mouth  Person  Animals
Head  Person  Animals
Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Arm  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Ear  Person  Animals
Ear  Person  Animals
Head  Person  Animals
Sheep  Animals
Neck  Sheep  Animals
Torso  Sheep  Animals
Head  Sheep  Animals
Dog  Animals
Tail  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Leg  Dog  Animals
Torso  Dog  Animals
Muzzle  Dog  Animals
Ear  Dog  Animals
Ear  Dog  Animals
Head  Dog  Animals
