Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Hand  Person  Animals
Torso  Person  Animals
Nose  Person  Animals
Mouth  Person  Animals
Eyebrow  Person  Animals
Eyebrow  Person  Animals
Eye  Person  Animals
Eye  Person  Animals
Head  Person  Animals
Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Head  Person  Animals
Person  Animals
Leg  Person  Animals
Foot  Person  Animals
Leg  Person  Animals
Hand  Person  Animals
Arm  Person  Animals
Torso  Person  Animals
Chair 
Chair 
Chair 
Chair 
TV_Monitor 
Screen  TV_Monitor 
Bottle 
Cap  Bottle 
Body  Bottle 
