variant 20 Cow  Animal
variant 114 Tail  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 70 Leg  Cow  Animal
variant 118 Torso  Cow  Animal
variant 84 Muzzle  Cow  Animal
variant 38 Eye  Cow  Animal
variant 38 Eye  Cow  Animal
variant 28 Ear  Cow  Animal
variant 28 Ear  Cow  Animal
variant 50 Head  Cow  Animal
variant 20 Cow  Animal
variant 91 Neck  Cow  Animal
variant 118 Torso  Cow  Animal
variant 84 Muzzle  Cow  Animal
variant 63 Horn  Cow  Animal
variant 63 Horn  Cow  Animal
variant 38 Eye  Cow  Animal
variant 38 Eye  Cow  Animal
variant 28 Ear  Cow  Animal
variant 50 Head  Cow  Animal
variant 6 Bird  Animal
variant 112 Tail  Bird  Animal
variant 68 Leg  Bird  Animal
variant 68 Leg  Bird  Animal
variant 1 Animal_Wing  Bird  Animal
variant 1 Animal_Wing  Bird  Animal
variant 88 Neck  Bird  Animal
variant 121 Torso  Bird  Animal
variant 4 Beak  Bird  Animal
variant 35 Eye  Bird  Animal
variant 47 Head  Bird  Animal
