Cow  Animal
Tail  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Leg  Cow  Animal
Torso  Cow  Animal
Muzzle  Cow  Animal
Eye  Cow  Animal
Eye  Cow  Animal
Ear  Cow  Animal
Ear  Cow  Animal
Head  Cow  Animal
Cow  Animal
Neck  Cow  Animal
Torso  Cow  Animal
Muzzle  Cow  Animal
Horn  Cow  Animal
Horn  Cow  Animal
Eye  Cow  Animal
Eye  Cow  Animal
Ear  Cow  Animal
Head  Cow  Animal
Bird  Animal
Tail  Bird  Animal
Leg  Bird  Animal
Leg  Bird  Animal
Animal_Wing  Bird  Animal
Animal_Wing  Bird  Animal
Neck  Bird  Animal
Torso  Bird  Animal
Beak  Bird  Animal
Eye  Bird  Animal
Head  Bird  Animal
