0 : Aeroplane , Vehicle
1 : Animal_Wing
2 : Animal_Wing , Animals , Bird
3 : Animals
4 : Arm
5 : Animals , Arm , Person
6 : Artifact_Wing
7 : Aeroplane , Vehicle , Artifact_Wing
8 : Beak
9 : Animals , Beak , Bird
10 : Vehicle , Bicycle
11 : Animals , Bird
12 : Boat , Vehicle
13 : Body
14 : Body , Bottle
15 : Aeroplane , Body , Vehicle
16 : Bodywork
17 : Bodywork , Vehicle , Bus
18 : Bodywork , Vehicle , Car
19 : Bottle
20 : Vehicle , Bus
21 : Bottle , Cap
22 : Cap
23 : Vehicle , Car
24 : Animals , Cat
25 : Chain_Wheel
26 : Chain_Wheel , Vehicle , Bicycle
27 : Chair
28 : Train , Vehicle , Coach
29 : Coach
30 : Animals , Cow
31 : Dining_Table
32 : Animals , Dog
33 : Vehicle , Bus , Door
34 : Vehicle , Car , Door
35 : Door
36 : Ear
37 : Animals , Cat , Ear
38 : Animals , Person , Ear
39 : Animals , Sheep , Ear
40 : Animals , Cow , Ear
41 : Animals , Dog , Ear
42 : Animals , Horse , Ear
43 : Aeroplane , Engine , Vehicle
44 : Engine
45 : Eye , Animals , Dog
46 : Eye , Animals
47 : Eye , Animals , Cat
48 : Eye , Animals , Bird
49 : Eye
50 : Eye , Animals , Horse
51 : Eye , Animals , Cow
52 : Eye , Animals , Sheep
53 : Eye , Animals , Person
54 : Eyebrow
55 : Eyebrow , Animals , Person
56 : Animals , Foot , Person
57 : Foot
58 : Animals , Hair , Person
59 : Hair
60 : Hand
61 : Animals , Person , Hand
62 : Motorbike , Vehicle , Handlebar
63 : Handlebar
64 : Vehicle , Bicycle , Handlebar
65 : Animals , Bird , Head
66 : Animals , Dog , Head
67 : Animals , Cat , Head
68 : Animals , Cow , Head
69 : Animals , Horse , Head
70 : Animals , Head
71 : Animals , Person , Head
72 : Head
73 : Animals , Sheep , Head
74 : Headlight , Vehicle , Bus
75 : Headlight
76 : Headlight , Train , Vehicle
77 : Motorbike , Vehicle , Headlight
78 : Headlight , Vehicle , Bicycle
79 : Headlight , Vehicle , Car
80 : Hoof
81 : Hoof , Animals , Horse
82 : Horn
83 : Cow , Horn , Animals
84 : Sheep , Horn , Animals
85 : Animals , Horse
86 : Animals , Leg , Dog
87 : Animals , Leg , Cat
88 : Animals , Leg
89 : Animals , Leg , Bird
90 : Animals , Cow , Leg
91 : Leg
92 : Animals , Sheep , Leg
93 : Animals , Horse , Leg
94 : Animals , Leg , Person
95 : Vehicle , License_Plate , Car
96 : Vehicle , Bus , License_Plate
97 : License_Plate
98 : Train , Vehicle , Locomotive
99 : Locomotive
100 : Vehicle , Bus , Mirror
101 : Mirror
102 : Vehicle , Car , Mirror
103 : Motorbike , Vehicle
104 : Mouth , Animals , Person
105 : Mouth
106 : Sheep , Muzzle , Animals
107 : Muzzle , Animals , Dog
108 : Cow , Muzzle , Animals
109 : Muzzle
110 : Horse , Muzzle , Animals
111 : Animals , Neck
112 : Animals , Neck , Cat
113 : Neck
114 : Sheep , Animals , Neck
115 : Animals , Neck , Bird
116 : Animals , Neck , Person
117 : Cow , Animals , Neck
118 : Animals , Neck , Dog
119 : Horse , Animals , Neck
120 : Animals , Nose , Dog
121 : Animals , Nose , Person
122 : Nose
123 : Animals , Person
124 : Plant
125 : Potted_Plant , Plant
126 : Potted_Plant , Pot
127 : Pot
128 : Potted_Plant
129 : Saddle
130 : Saddle , Vehicle , Bicycle
131 : Motorbike , Saddle , Vehicle
132 : Screen
133 : Screen , TV_Monitor
134 : Animals , Sheep
135 : Sofa
136 : Aeroplane , Vehicle , Stern
137 : Stern
138 : TV_Monitor
139 : Animals , Dog , Tail
140 : Animals , Cat , Tail
141 : Animals , Cow , Tail
142 : Tail
143 : Animals , Sheep , Tail
144 : Animals , Horse , Tail
145 : Animals , Bird , Tail
146 : Torso , Animals , Person
147 : Torso
148 : Torso , Animals , Sheep
149 : Torso , Animals , Bird
150 : Torso , Animals , Dog
151 : Torso , Animals , Cat
152 : Torso , Animals , Cow
153 : Torso , Animals , Horse
154 : Torso , Animals
155 : Train , Vehicle
156 : Vehicle
157 : Aeroplane , Vehicle , Wheel
158 : Vehicle , Wheel , Bicycle
159 : Motorbike , Vehicle , Wheel
160 : Wheel
161 : Vehicle , Wheel , Car
162 : Vehicle , Wheel , Bus
163 : Window
164 : Vehicle , Window , Car
165 : Vehicle , Bus , Window
